import { describe, expect, it } from 'vitest'
import { createHash } from 'node:crypto'
import { nativeBaselineJpegDimensions } from './nativeJpegV1.js'
import { decodeNativeDocxPagePaintResourceListV1 } from './nativeImagePagePaintV1.js'

// Generated by Go image/jpeg for a 16x8 red/blue test pattern, with an explicit
// JFIF APP0 header. No third-party photograph or encoder-dependent golden pixels.
const JPEG = Uint8Array.from(Buffer.from('/9j/4AAQSkZJRgABAgAAAQABAAD/2wCEAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgoBAgICAgICBQMDBQoHBgcKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCv/AABEIAAgAEAMBIgACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/APneuLrtK4uv2D6Hf/M8/wC5b/3YP2z6cn/NP/8Ac3/7rH//2Q==', 'base64'))
function marker(code: number) { return JPEG.findIndex((byte, index) => byte === 0xff && JPEG[index + 1] === code) }
describe('bounded native baseline JFIF', () => {
  it('refuses invalid baseline AC symbols and complete Huffman trees', () => {
    const dht = marker(0xc4), end = dht + 2 + JPEG[dht + 2]! * 256 + JPEG[dht + 3]!
    let acSymbol = -1
    for (let at = dht + 4; at < end;) {
      const table = JPEG[at++]!
      const count = JPEG.subarray(at, at + 16).reduce((sum, value) => sum + value, 0)
      at += 16
      if (table >>> 4 === 1) { acSymbol = at; break }
      at += count
    }
    expect(acSymbol).toBeGreaterThan(0)
    for (const symbol of [0x0b, 0xff, 0x10, 0xe0]) {
      const invalid = JPEG.slice(); invalid[acSymbol] = symbol
      expect(nativeBaselineJpegDimensions(invalid)).toBeUndefined()
    }
    // Keep all twelve original DC symbols/segment lengths, but assign four
    // length-three and eight length-four codes: the latter consumes 1111.
    const complete = JPEG.slice()
    complete.fill(0, dht + 5, dht + 21)
    complete[dht + 7] = 4
    complete[dht + 8] = 8
    expect(nativeBaselineJpegDimensions(complete)).toBeUndefined()
  })
  it('validates MIME, dimensions, digest and canonical JPEG resource identity', () => {
    const hash = (value: string | Uint8Array) => createHash('sha256').update(value).digest('hex')
    const part = 'word/media/bands.jpg', digest = hash(JPEG)
    const asset = { id: `image:${digest}:${hash(part)}`, part_name: part, content_type: 'image/jpeg', content_digest: `sha256:${digest}`, byte_length: JPEG.length, width_px: 16, height_px: 8, bytes_base64: Buffer.from(JPEG).toString('base64') }
    expect(decodeNativeDocxPagePaintResourceListV1([asset])).toEqual([asset])
    for (const patch of [{ width_px: 32 }, { content_type: 'image/png' }, { content_digest: `sha256:${'0'.repeat(64)}` }]) expect(() => decodeNativeDocxPagePaintResourceListV1([{ ...asset, ...patch }])).toThrow()
  })
  it('reads baseline dimensions without modifying bytes', () => {
    const before = JPEG.slice()
    expect(nativeBaselineJpegDimensions(JPEG)).toEqual({ width: 16, height: 8 })
    expect(JPEG).toEqual(before)
  })
  it('refuses truncation and data after the end marker', () => {
    for (let length = 0; length < JPEG.length; length++) expect(nativeBaselineJpegDimensions(JPEG.subarray(0,length))).toBeUndefined()
    expect(nativeBaselineJpegDimensions(Uint8Array.from([...JPEG, 0]))).toBeUndefined()
  })
  it('refuses ambiguous metadata, progressive coding and non-YCbCr component IDs', () => {
    for (const app of [0xe1, 0xe2, 0xee]) {
      expect(nativeBaselineJpegDimensions(Uint8Array.from([...JPEG.subarray(0,20), 0xff,app,0,2,...JPEG.subarray(20)]))).toBeUndefined()
    }
    const progressive = JPEG.slice(); progressive[marker(0xc0)+1] = 0xc2
    expect(nativeBaselineJpegDimensions(progressive)).toBeUndefined()
    const rgb = JPEG.slice(); rgb[marker(0xc0)+10] = 82
    expect(nativeBaselineJpegDimensions(rgb)).toBeUndefined()
  })
  it('refuses missing quantization/Huffman tables, extra scans and invalid dimensions', () => {
    for (const [at,value] of [[marker(0xda)+6,0x33], [marker(0xc0)+12,3], [marker(0xc0)+8,0], [marker(0xda)+12,1]]) {
      const malformed = JPEG.slice(); malformed[at!] = value!
      expect(nativeBaselineJpegDimensions(malformed)).toBeUndefined()
    }
    const multiscan = JPEG.slice(); multiscan[multiscan.length-1] = 0xda
    expect(nativeBaselineJpegDimensions(multiscan)).toBeUndefined()
  })
})
