import { describe, expect, it } from 'vitest'
import { createHash } from 'node:crypto'
import { crc32 } from 'node:zlib'
import { nativeBaselineJpegDimensions } from './nativeJpegV1.js'
import { decodeNativeDocxPagePaintResourceListV1, prepareNativeRasterResourceV1 } from './nativeImagePagePaintV1.js'

const PNG = Uint8Array.from(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64'))

// Generated by Go image/jpeg for a 16x8 red/blue test pattern, with an explicit
// JFIF APP0 header. No third-party photograph or encoder-dependent golden pixels.
const JPEG = Uint8Array.from(Buffer.from('/9j/4AAQSkZJRgABAgAAAQABAAD/2wCEAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgoBAgICAgICBQMDBQoHBgcKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCv/AABEIAAgAEAMBIgACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/APneuLrtK4uv2D6Hf/M8/wC5b/3YP2z6cn/NP/8Ac3/7rH//2Q==', 'base64'))
function marker(code: number) { return JPEG.findIndex((byte, index) => byte === 0xff && JPEG[index + 1] === code) }
/** An Exif APP1 segment whose IFD0 carries the given [tag, type, count, inline
 * value] entries, in either TIFF byte order. */
function exifApp1(entries: readonly (readonly [number, number, number, number])[], order: 'MM' | 'II' = 'MM'): Uint8Array {
  const big = order === 'MM'
  const short = (value: number) => big ? [value >>> 8, value & 255] : [value & 255, value >>> 8]
  const long = (value: number) => big ? [0, 0, value >>> 8, value & 255] : [value & 255, value >>> 8, 0, 0]
  const body = [0x45, 0x78, 0x69, 0x66, 0, 0, ...(big ? [0x4d, 0x4d] : [0x49, 0x49]), ...short(42), ...long(8), ...short(entries.length)]
  // TIFF left-justifies an inline SHORT inside its four value bytes.
  for (const [tag, type, count, value] of entries) body.push(...short(tag), ...short(type), ...long(count), ...short(value), 0, 0)
  body.push(0, 0, 0, 0)
  return Uint8Array.from([0xff, 0xe1, (body.length + 2) >>> 8, (body.length + 2) & 255, ...body])
}
/** Splice a header segment in directly after the JFIF APP0. */
const afterApp0 = (segment: Uint8Array) => Uint8Array.from([...JPEG.subarray(0, 20), ...segment, ...JPEG.subarray(20)])
describe('bounded native baseline JFIF', () => {
  it('refuses invalid baseline AC symbols and complete Huffman trees', () => {
    const dht = marker(0xc4), end = dht + 2 + JPEG[dht + 2]! * 256 + JPEG[dht + 3]!
    let acSymbol = -1
    for (let at = dht + 4; at < end;) {
      const table = JPEG[at++]!
      const count = JPEG.subarray(at, at + 16).reduce((sum, value) => sum + value, 0)
      at += 16
      if (table >>> 4 === 1) { acSymbol = at; break }
      at += count
    }
    expect(acSymbol).toBeGreaterThan(0)
    for (const symbol of [0x0b, 0xff, 0x10, 0xe0]) {
      const invalid = JPEG.slice(); invalid[acSymbol] = symbol
      expect(nativeBaselineJpegDimensions(invalid)).toBeUndefined()
    }
    // Keep all twelve original DC symbols/segment lengths, but assign four
    // length-three and eight length-four codes: the latter consumes 1111.
    const complete = JPEG.slice()
    complete.fill(0, dht + 5, dht + 21)
    complete[dht + 7] = 4
    complete[dht + 8] = 8
    expect(nativeBaselineJpegDimensions(complete)).toBeUndefined()
  })
  it('validates MIME, dimensions, digest and canonical JPEG resource identity', () => {
    const hash = (value: string | Uint8Array) => createHash('sha256').update(value).digest('hex')
    const part = 'word/media/bands.jpg', digest = hash(JPEG)
    const asset = { id: `image:${digest}:${hash(part)}`, part_name: part, content_type: 'image/jpeg', content_digest: `sha256:${digest}`, byte_length: JPEG.length, width_px: 16, height_px: 8, bytes_base64: Buffer.from(JPEG).toString('base64') }
    expect(decodeNativeDocxPagePaintResourceListV1([asset])).toEqual([asset])
    for (const patch of [{ width_px: 32 }, { content_type: 'image/png' }, { content_digest: `sha256:${'0'.repeat(64)}` }]) expect(() => decodeNativeDocxPagePaintResourceListV1([{ ...asset, ...patch }])).toThrow()
  })
  it('reads baseline dimensions without modifying bytes', () => {
    const before = JPEG.slice()
    expect(nativeBaselineJpegDimensions(JPEG)).toEqual({ width: 16, height: 8 })
    expect(JPEG).toEqual(before)
  })
  it('refuses truncation and data after the end marker', () => {
    for (let length = 0; length < JPEG.length; length++) expect(nativeBaselineJpegDimensions(JPEG.subarray(0,length))).toBeUndefined()
    expect(nativeBaselineJpegDimensions(Uint8Array.from([...JPEG, 0]))).toBeUndefined()
  })
  it('refuses ambiguous metadata, progressive coding and non-YCbCr component IDs', () => {
    for (const app of [0xe1, 0xe2, 0xee]) {
      expect(nativeBaselineJpegDimensions(Uint8Array.from([...JPEG.subarray(0,20), 0xff,app,0,2,...JPEG.subarray(20)]))).toBeUndefined()
    }
    const progressive = JPEG.slice(); progressive[marker(0xc0)+1] = 0xc2
    expect(nativeBaselineJpegDimensions(progressive)).toBeUndefined()
    const rgb = JPEG.slice(); rgb[marker(0xc0)+10] = 82
    expect(nativeBaselineJpegDimensions(rgb)).toBeUndefined()
  })
  it('reads an otherwise baseline JPEG that carries a non-rotating Exif segment', () => {
    // ppt/media/image1.png in customxml.pptx is exactly this: JFIF APP0, then an
    // Exif APP1 holding an ExifIFDPointer and a UserComment, then baseline data.
    const resolutionUnit = afterApp0(exifApp1([[0x0128, 3, 1, 2]]))
    expect(nativeBaselineJpegDimensions(resolutionUnit)).toEqual({ width: 16, height: 8 })
    expect(nativeBaselineJpegDimensions(afterApp0(exifApp1([[0x0112, 3, 1, 1]])))).toEqual({ width: 16, height: 8 })
    expect(nativeBaselineJpegDimensions(afterApp0(exifApp1([[0x0112, 3, 1, 1]], 'II')))).toEqual({ width: 16, height: 8 })
    expect(nativeBaselineJpegDimensions(afterApp0(exifApp1([[0x8769, 4, 1, 0x1a], [0x0112, 3, 1, 1]])))).toEqual({ width: 16, height: 8 })
  })
  it('refuses a rotating, repeated, misplaced or malformed Exif segment', () => {
    // A browser applies EXIF orientation, so anything but the identity would
    // paint a rotated or mirrored raster where the source page has neither.
    for (const orientation of [0, 2, 3, 4, 5, 6, 7, 8, 9]) {
      expect(nativeBaselineJpegDimensions(afterApp0(exifApp1([[0x0112, 3, 1, orientation]]))), `orientation ${orientation}`).toBeUndefined()
      expect(nativeBaselineJpegDimensions(afterApp0(exifApp1([[0x0112, 3, 1, orientation]], 'II'))), `orientation ${orientation} II`).toBeUndefined()
    }
    // Orientation smuggled in under another TIFF type or count.
    for (const entry of [[0x0112, 4, 1, 1], [0x0112, 3, 2, 1], [0x0112, 1, 1, 1]] as const) {
      expect(nativeBaselineJpegDimensions(afterApp0(exifApp1([entry]))), JSON.stringify(entry)).toBeUndefined()
    }
    const exif = exifApp1([[0x0128, 3, 1, 2]])
    expect(nativeBaselineJpegDimensions(afterApp0(Uint8Array.from([...exif, ...exif])))).toBeUndefined()
    // An APP1 that is not Exif at all, an empty IFD0, and a truncated payload.
    const xmp = Uint8Array.from([0xff, 0xe1, 0, 12, 0x68, 0x74, 0x74, 0x70, 0x3a, 0x2f, 0x2f, 0x78, 0, 0])
    expect(nativeBaselineJpegDimensions(afterApp0(xmp))).toBeUndefined()
    expect(nativeBaselineJpegDimensions(afterApp0(exifApp1([])))).toBeUndefined()
    for (let drop = 1; drop < 18; drop += 1) {
      const short = exif.slice(0, exif.length - drop)
      short[2] = (short.length - 2) >>> 8; short[3] = (short.length - 2) & 255
      expect(nativeBaselineJpegDimensions(afterApp0(short)), `truncated by ${drop}`).toBeUndefined()
    }
    // Exif ahead of the JFIF APP0, and Exif behind the frame header.
    expect(nativeBaselineJpegDimensions(Uint8Array.from([...JPEG.subarray(0, 2), ...exif, ...JPEG.subarray(2)]))).toBeUndefined()
    const sof = marker(0xc0)
    expect(nativeBaselineJpegDimensions(Uint8Array.from([...JPEG.subarray(0, sof + 2 + JPEG[sof + 2]! * 256 + JPEG[sof + 3]!), ...exif, ...JPEG.subarray(sof + 2 + JPEG[sof + 2]! * 256 + JPEG[sof + 3]!)]))).toBeUndefined()
    // A valid Exif segment does not excuse the rest of the frame.
    const progressive = afterApp0(exif)
    progressive[progressive.findIndex((byte, index) => byte === 0xff && progressive[index + 1] === 0xc0) + 1] = 0xc2
    expect(nativeBaselineJpegDimensions(progressive)).toBeUndefined()
  })
  it('reads a raster format from its signature, never from the declared media type', () => {
    // customxml.pptx types and names ppt/media/image1.png a PNG and stores an
    // Exif JPEG in it. The declared type cannot select the decoder.
    const mistyped = prepareNativeRasterResourceV1('ppt/media/image1.png', 'image/png', afterApp0(exifApp1([[0x0128, 3, 1, 2]])))
    expect(mistyped).toMatchObject({ part_name: 'ppt/media/image1.png', content_type: 'image/jpeg', width_px: 16, height_px: 8 })
    expect(decodeNativeDocxPagePaintResourceListV1([mistyped])).toEqual([mistyped])
    expect(prepareNativeRasterResourceV1('word/media/image1.jpeg', 'image/jpeg', PNG)).toMatchObject({ content_type: 'image/png', width_px: 1, height_px: 1 })
    expect(prepareNativeRasterResourceV1('ppt/media/image1.png', 'image/png', PNG)).toMatchObject({ content_type: 'image/png' })

    // Sniffing decides which rules apply, never whether they apply.
    const chunk = (type: string, data: readonly number[]) => {
      const body = [...[...type].map((character) => character.charCodeAt(0)), ...data]
      const sum = crc32(Uint8Array.from(body))
      return [data.length >>> 24 & 255, data.length >>> 16 & 255, data.length >>> 8 & 255, data.length & 255, ...body, sum >>> 24 & 255, sum >>> 16 & 255, sum >>> 8 & 255, sum & 255]
    }
    const animated = Uint8Array.from([...PNG.subarray(0, 33), ...chunk('acTL', [0, 0, 0, 2, 0, 0, 0, 0]), ...PNG.subarray(33)])
    const progressive = JPEG.slice(); progressive[marker(0xc0) + 1] = 0xc2
    const truncated = JPEG.subarray(0, JPEG.length - 4)
    const gif = Uint8Array.from([0x47, 0x49, 0x46, 0x38, 0x39, 0x61, ...PNG.subarray(6)])
    for (const [label, bytes] of [['animated PNG', animated], ['progressive JPEG', progressive], ['truncated JPEG', truncated], ['truncated PNG', PNG.subarray(0, PNG.length - 4)], ['GIF', gif]] as const) {
      expect(() => prepareNativeRasterResourceV1('ppt/media/image1.png', 'image/png', bytes), label).toThrow('Native raster must be a complete static PNG or baseline JFIF JPEG')
      expect(() => prepareNativeRasterResourceV1('ppt/media/image1.jpg', 'image/jpeg', bytes), label).toThrow('Native raster must be a complete static PNG or baseline JFIF JPEG')
    }
    expect(() => prepareNativeRasterResourceV1('ppt/media/image1.png', 'image/gif' as 'image/png', PNG)).toThrow('identity or byte budget is invalid')

    // Reading the format from the signature is not a licence to read the rest
    // loosely. customxml.pptx's own ppt/media/image1.png still refuses on both
    // counts it fails independently of its name: a zero JFIF density pair, and
    // 264 bytes trailing its EOI marker.
    const zeroDensity = JPEG.slice(); zeroDensity.fill(0, 14, 18)
    expect(nativeBaselineJpegDimensions(zeroDensity)).toBeUndefined()
    expect(nativeBaselineJpegDimensions(Uint8Array.from([...JPEG, 0x10, 0x08, 0x04, 0x02]))).toBeUndefined()
  })
  it('refuses missing quantization/Huffman tables, extra scans and invalid dimensions', () => {
    for (const [at,value] of [[marker(0xda)+6,0x33], [marker(0xc0)+12,3], [marker(0xc0)+8,0], [marker(0xda)+12,1]]) {
      const malformed = JPEG.slice(); malformed[at!] = value!
      expect(nativeBaselineJpegDimensions(malformed)).toBeUndefined()
    }
    const multiscan = JPEG.slice(); multiscan[multiscan.length-1] = 0xda
    expect(nativeBaselineJpegDimensions(multiscan)).toBeUndefined()
  })
})
