export { canonicalizeNativePptx, stringifyNativePptx } from './canonical'
export { assertNativePptx, validateNativePptx } from './validate'
export type { NativeValidationIssue } from './validate'
export {
  PPTX_NATIVE_CONTRACT_VERSION,
  PPTX_NATIVE_RESOURCE_LIMITS,
  PPTX_NATIVE_SCHEMA,
  PPTX_NATIVE_SCHEMA_ID,
  PPTX_NATIVE_SCHEMA_SHA256,
  animationEffectValues,
  compatibilityStatusValues,
  diagnosticSeverityValues,
  directionValues,
  elementKindValues,
  originValues,
  provenanceValues,
  passthroughDispositionValues,
  placeholderTypeValues,
  shapePresetValues,
  textAlignValues,
  textVerticalAnchorValues,
  textWrapValues,
  transitionTypeValues,
} from './schema.generated'
export type {
  NativeAnimation,
  NativeAnimationEffect,
  NativeAsset,
  NativeChartElement,
  NativeCompatibility,
  NativeCompatibilityStatus,
  NativeConnectorElement,
  NativeDiagnostic,
  NativeDiagnosticScope,
  NativeDiagnosticSeverity,
  NativeDirection,
  NativeElement,
  NativeElementKind,
  NativeGroupElement,
  NativeOpaqueChart,
  NativePictureCrop,
  NativeOrigin,
  NativeProvenance,
  NativeParagraph,
  NativePassthroughDisposition,
  NativePassthroughRef,
  NativePictureElement,
  NativePlaceholderType,
  NativePptxDeck,
  NativeShapeElement,
  NativeShapePreset,
  NativeSize,
  NativeSlide,
  NativeSourceAnchor,
  NativeStroke,
  NativeTable,
  NativeTableBorder,
  NativeTableCell,
  NativeTableElement,
  NativeTextAlign,
  NativeTextBodyLayout,
  NativeTextElement,
  NativeTextRun,
  NativeTextVerticalAnchor,
  NativeTextWrap,
  NativeTransition,
  NativeTransitionType,
  NativeTransform,
} from './types'
