// Code generated by scripts/generate-pptx-native-contract.mjs; DO NOT EDIT.
// Source: ../../schemas/pptx-native-v1.schema.json

package pptxpatch

const NativePPTXContractVersion = "pptx-native/v1"
const NativePPTXSchemaID = "https://injoffice.dev/schemas/pptx-native-v1.schema.json"
const NativePPTXSchemaSHA256 = "dc42f7a99f6f272bd68d4946de1248dcc01f06586e061249715506cf9ccea665"
const nativeMaxJsonBytes = 268435456
const nativeMaxNodes = 1000000
const nativeMaxDepth = 64
const nativeMaxAssets = 4096
const nativeMaxSlides = 4096
const nativeMaxElementsPerContainer = 10000
const nativeMaxTotalElements = 100000
const nativeMaxParagraphsPerElement = 10000
const nativeMaxRunsPerParagraph = 100000
const nativeMaxTextCodeUnits = 1048576
const nativeMaxTotalTextCodeUnits = 16777216
const nativeMaxTableRows = 10000
const nativeMaxTableColumns = 16384
const nativeMaxTableCells = 1000000
const nativeMaxPassthroughPerObject = 10000
const nativeMaxDiagnosticsPerScope = 1000
const nativeMaxLineWidthEmu = 20116800
const nativeMaxDrawingPercentage = 2147483647
const nativeMaxAssetBytes = 536870912
const nativeMaxInlineAssetBase64CodeUnits = 89478488
const nativeMaxTotalInlineAssetBase64CodeUnits = 134217728

type nativePPTXBindingShape struct {
	Properties []string
	Required   []string
}

var nativePPTXBindingShapes = map[string]nativePPTXBindingShape{
	"NativeAnimation": {
		Properties: []string{"delayMs", "direction", "distancePpm", "durationMs", "effect"},
		Required:   []string{"effect"},
	},
	"NativeAreaSourceBaseline": {
		Properties: []string{"crossing", "value"},
		Required:   []string{"crossing", "value"},
	},
	"NativeArrowEnd": {
		Properties: []string{"len", "type", "w"},
		Required:   []string{"type"},
	},
	"NativeAsset": {
		Properties: []string{"byteLength", "contentType", "dataBase64", "id", "passthrough", "provenance", "sha256", "source"},
		Required:   []string{"byteLength", "contentType", "id", "passthrough", "provenance", "sha256"},
	},
	"NativeChartAxisLabels": {
		Properties: []string{"majorTickMark", "majorUnit", "numberFormat", "position", "profile", "style"},
		Required:   []string{"majorTickMark", "position", "profile", "style"},
	},
	"NativeChartAxisLabelStyle": {
		Properties: []string{"bold", "color", "fontFamily", "fontSize", "italic", "language"},
		Required:   []string{"bold", "color", "fontFamily", "fontSize", "italic", "language"},
	},
	"NativeChartElement": {
		Properties: []string{"animation", "chart", "compatibility", "graphicFrameLayout", "id", "kind", "name", "passthrough", "provenance", "source", "transform"},
		Required:   []string{"chart", "compatibility", "id", "kind", "passthrough", "provenance", "source", "transform"},
	},
	"NativeCompatibility": {
		Properties: []string{"diagnostics", "status"},
		Required:   []string{"diagnostics", "status"},
	},
	"NativeConnectorElement": {
		Properties: []string{"animation", "compatibility", "flipH", "geometry", "headArrow", "headEnd", "id", "kind", "name", "passthrough", "provenance", "source", "stroke", "tailArrow", "tailEnd", "transform"},
		Required:   []string{"compatibility", "id", "kind", "passthrough", "provenance", "transform"},
	},
	"NativeDiagnostic": {
		Properties: []string{"code", "message", "scope", "severity"},
		Required:   []string{"code", "message", "severity"},
	},
	"NativeDiagnosticScope": {
		Properties: []string{"elementId", "partName", "slideId"},
		Required:   []string{},
	},
	"NativeEvaluatedGeometry": {
		Properties: []string{"paths", "profile", "textRect"},
		Required:   []string{"paths", "profile", "textRect"},
	},
	"NativeGeometryCommand": {
		Properties: []string{"clockwise", "kind", "largeArc", "rx", "ry", "x", "x1", "x2", "y", "y1", "y2"},
		Required:   []string{"kind"},
	},
	"NativeGeometryPath": {
		Properties: []string{"commands", "fillMode", "stroke"},
		Required:   []string{"commands", "fillMode", "stroke"},
	},
	"NativeGeometryTextRect": {
		Properties: []string{"cx", "cy", "x", "y"},
		Required:   []string{"cx", "cy", "x", "y"},
	},
	"NativeGroupElement": {
		Properties: []string{"animation", "childTransform", "children", "compatibility", "id", "kind", "name", "passthrough", "provenance", "source", "transform"},
		Required:   []string{"children", "compatibility", "id", "kind", "passthrough", "provenance", "transform"},
	},
	"NativeLiteralArea": {
		Properties: []string{"categories", "dataOrigin", "grouping", "profile", "series", "sourceBaseline", "xAxis", "yAxis"},
		Required:   []string{"categories", "dataOrigin", "grouping", "profile", "series", "xAxis", "yAxis"},
	},
	"NativeLiteralAreaSeries": {
		Properties: []string{"color", "index", "order", "title", "values"},
		Required:   []string{"color", "index", "order", "values"},
	},
	"NativeLiteralBar": {
		Properties: []string{"barDirection", "categories", "categoryAxis", "dataOrigin", "gapWidth", "grouping", "overlap", "profile", "series", "valueAxis"},
		Required:   []string{"barDirection", "categories", "categoryAxis", "dataOrigin", "gapWidth", "grouping", "overlap", "profile", "series", "valueAxis"},
	},
	"NativeLiteralBarAxis": {
		Properties: []string{"color", "crossAxisId", "crossesAt", "deleted", "id", "labels", "max", "min", "orientation", "position", "widthEmu"},
		Required:   []string{"crossAxisId", "deleted", "id", "orientation", "position"},
	},
	"NativeLiteralBarSeries": {
		Properties: []string{"colors", "index", "order", "title", "values"},
		Required:   []string{"colors", "index", "order", "values"},
	},
	"NativeLiteralBubble": {
		Properties: []string{"bubbleScale", "dataOrigin", "profile", "series", "sizeRepresents", "xAxis", "yAxis"},
		Required:   []string{"bubbleScale", "dataOrigin", "profile", "series", "sizeRepresents", "xAxis", "yAxis"},
	},
	"NativeLiteralBubbleSeries": {
		Properties: []string{"colors", "index", "order", "sizes", "title", "values", "xValues"},
		Required:   []string{"colors", "index", "order", "sizes", "values", "xValues"},
	},
	"NativeLiteralConnected": {
		Properties: []string{"categories", "dataOrigin", "profile", "series", "xAxis", "yAxis"},
		Required:   []string{"categories", "dataOrigin", "profile", "series", "xAxis", "yAxis"},
	},
	"NativeLiteralConnectedSeries": {
		Properties: []string{"color", "index", "order", "title", "values", "widthEmu", "xValues"},
		Required:   []string{"color", "index", "order", "values", "widthEmu"},
	},
	"NativeLiteralDoughnut": {
		Properties: []string{"colors", "firstSliceAngle", "holeSize", "profile", "values"},
		Required:   []string{"colors", "firstSliceAngle", "holeSize", "profile", "values"},
	},
	"NativeLiteralPie": {
		Properties: []string{"colors", "firstSliceAngle", "profile", "values"},
		Required:   []string{"colors", "firstSliceAngle", "profile", "values"},
	},
	"NativeLiteralRadar": {
		Properties: []string{"categories", "categoryAxis", "dataOrigin", "profile", "series", "style", "valueAxis"},
		Required:   []string{"categories", "categoryAxis", "dataOrigin", "profile", "series", "style", "valueAxis"},
	},
	"NativeLiteralRadarSeries": {
		Properties: []string{"color", "fill", "index", "order", "title", "values", "widthEmu"},
		Required:   []string{"color", "index", "order", "values", "widthEmu"},
	},
	"NativeLiteralStackedBar": {
		Properties: []string{"barDirection", "categories", "categoryAxis", "dataOrigin", "gapWidth", "grouping", "overlap", "profile", "series", "valueAxis"},
		Required:   []string{"barDirection", "categories", "categoryAxis", "dataOrigin", "gapWidth", "grouping", "overlap", "profile", "series", "valueAxis"},
	},
	"NativeLiteralStackedLine": {
		Properties: []string{"categories", "dataOrigin", "grouping", "profile", "series", "xAxis", "yAxis"},
		Required:   []string{"categories", "dataOrigin", "grouping", "profile", "series", "xAxis", "yAxis"},
	},
	"NativeOpaqueChart": {
		Properties: []string{"chartPart", "literalArea", "literalBar", "literalBubble", "literalConnected", "literalDoughnut", "literalPie", "literalRadar", "literalStackedBar", "literalStackedLine", "opaqueRef", "previewAssetId", "relationshipId"},
		Required:   []string{"chartPart", "opaqueRef", "relationshipId"},
	},
	"NativeParagraph": {
		Properties: []string{"align", "bullet", "bulletCharacter", "bulletFontEncoding", "bulletFontFamily", "indentEmu", "level", "lineSpacingEmu", "lineSpacingPercent1000", "marginLeftEmu", "runs", "spaceAfterEmu", "spaceBeforeEmu"},
		Required:   []string{"runs"},
	},
	"NativePassthroughRef": {
		Properties: []string{"disposition", "fingerprintSha256", "ownerPart", "token"},
		Required:   []string{"disposition", "fingerprintSha256", "ownerPart", "token"},
	},
	"NativePictureCrop": {
		Properties: []string{"bottom", "left", "right", "top"},
		Required:   []string{"bottom", "left", "right", "top"},
	},
	"NativePictureElement": {
		Properties: []string{"animation", "assetId", "clip", "compatibility", "crop", "geometry", "id", "kind", "name", "passthrough", "provenance", "source", "transform"},
		Required:   []string{"assetId", "compatibility", "id", "kind", "passthrough", "provenance", "transform"},
	},
	"NativePptxDeck": {
		Properties: []string{"assets", "compatibility", "contractVersion", "documentId", "origin", "size", "slides", "sourceRevision"},
		Required:   []string{"assets", "compatibility", "contractVersion", "documentId", "origin", "size", "slides"},
	},
	"NativeShapeElement": {
		Properties: []string{"animation", "compatibility", "fill", "geometry", "id", "kind", "name", "paragraphs", "passthrough", "placeholder", "preset", "provenance", "source", "stroke", "textBody", "transform"},
		Required:   []string{"compatibility", "id", "kind", "paragraphs", "passthrough", "provenance", "transform"},
	},
	"NativeSize": {
		Properties: []string{"cx", "cy"},
		Required:   []string{"cx", "cy"},
	},
	"NativeSlide": {
		Properties: []string{"background", "compatibility", "elements", "id", "passthrough", "provenance", "source", "transition"},
		Required:   []string{"compatibility", "elements", "id", "passthrough", "provenance"},
	},
	"NativeSourceAnchor": {
		Properties: []string{"fingerprintSha256", "objectId", "partName", "relationshipId"},
		Required:   []string{"fingerprintSha256", "objectId", "partName"},
	},
	"NativeStroke": {
		Properties: []string{"cap", "color", "dash", "join", "miterLimit", "widthEmu"},
		Required:   []string{"color", "widthEmu"},
	},
	"NativeTable": {
		Properties: []string{"columnWidths", "rowHeights", "rows"},
		Required:   []string{"columnWidths", "rowHeights", "rows"},
	},
	"NativeTableBorder": {
		Properties: []string{"color", "widthEmu"},
		Required:   []string{"color", "widthEmu"},
	},
	"NativeTableCell": {
		Properties: []string{"align", "border", "fill", "paragraphs", "text", "textBody"},
		Required:   []string{"text"},
	},
	"NativeTableElement": {
		Properties: []string{"animation", "compatibility", "graphicFrameLayout", "id", "kind", "name", "passthrough", "provenance", "source", "table", "transform"},
		Required:   []string{"compatibility", "id", "kind", "passthrough", "provenance", "table", "transform"},
	},
	"NativeTextBodyLayout": {
		Properties: []string{"autoFit", "bottomInsetEmu", "columnCount", "columnSpacingEmu", "horizontalOverflow", "leftInsetEmu", "lineSpacingReductionPercent1000", "presetTextWarp", "presetTextWarpAdj", "rightInsetEmu", "rotationAngle60000", "topInsetEmu", "upright", "verticalAnchor", "verticalOverflow", "wrap", "writingMode"},
		Required:   []string{"autoFit", "bottomInsetEmu", "horizontalOverflow", "leftInsetEmu", "rightInsetEmu", "topInsetEmu", "verticalAnchor", "verticalOverflow", "wrap"},
	},
	"NativeTextElement": {
		Properties: []string{"animation", "compatibility", "id", "kind", "name", "paragraphs", "passthrough", "placeholder", "provenance", "source", "textBody", "transform"},
		Required:   []string{"compatibility", "id", "kind", "paragraphs", "passthrough", "provenance", "transform"},
	},
	"NativeTextRun": {
		Properties: []string{"bold", "color", "fontFamily", "fontSizeHundredthPt", "italic", "kerningThresholdHundredthPt", "language", "text"},
		Required:   []string{"text"},
	},
	"NativeTransform": {
		Properties: []string{"cx", "cy", "flipH", "flipV", "quarterTurns", "rotationAngle", "x", "y"},
		Required:   []string{"cx", "cy", "x", "y"},
	},
	"NativeTransition": {
		Properties: []string{"direction", "type"},
		Required:   []string{"type"},
	},
}

type NativeOrigin string

const NativeOriginAuthored NativeOrigin = "authored"
const NativeOriginParsed NativeOrigin = "parsed"

type NativeProvenance string

const NativeProvenanceAuthored NativeProvenance = "authored"
const NativeProvenanceParsed NativeProvenance = "parsed"

type NativeCompatibilityStatus string

const NativeCompatibilityStatusEditable NativeCompatibilityStatus = "editable"
const NativeCompatibilityStatusPreserveOnly NativeCompatibilityStatus = "preserveOnly"
const NativeCompatibilityStatusRefused NativeCompatibilityStatus = "refused"

type NativeDiagnosticSeverity string

const NativeDiagnosticSeverityInfo NativeDiagnosticSeverity = "info"
const NativeDiagnosticSeverityWarning NativeDiagnosticSeverity = "warning"
const NativeDiagnosticSeverityRefusal NativeDiagnosticSeverity = "refusal"

type NativePassthroughDisposition string

const NativePassthroughDispositionPreserve NativePassthroughDisposition = "preserve"
const NativePassthroughDispositionReplaceOnEdit NativePassthroughDisposition = "replaceOnEdit"

type NativeElementKind string

const NativeElementKindText NativeElementKind = "text"
const NativeElementKindShape NativeElementKind = "shape"
const NativeElementKindConnector NativeElementKind = "connector"
const NativeElementKindPicture NativeElementKind = "picture"
const NativeElementKindTable NativeElementKind = "table"
const NativeElementKindChart NativeElementKind = "chart"
const NativeElementKindGroup NativeElementKind = "group"

type NativePlaceholderType string

const NativePlaceholderTypeTitle NativePlaceholderType = "title"
const NativePlaceholderTypeCtrTitle NativePlaceholderType = "ctrTitle"
const NativePlaceholderTypeSubTitle NativePlaceholderType = "subTitle"
const NativePlaceholderTypeBody NativePlaceholderType = "body"

type NativeShapePreset string

const NativeShapePresetRect NativeShapePreset = "rect"
const NativeShapePresetRoundRect NativeShapePreset = "roundRect"
const NativeShapePresetEllipse NativeShapePreset = "ellipse"
const NativeShapePresetTriangle NativeShapePreset = "triangle"
const NativeShapePresetDiamond NativeShapePreset = "diamond"
const NativeShapePresetRightArrow NativeShapePreset = "rightArrow"
const NativeShapePresetPentagon NativeShapePreset = "pentagon"
const NativeShapePresetHexagon NativeShapePreset = "hexagon"
const NativeShapePresetStar5 NativeShapePreset = "star5"

type NativeStrokeCap string

const NativeStrokeCapFlat NativeStrokeCap = "flat"
const NativeStrokeCapRound NativeStrokeCap = "round"
const NativeStrokeCapSquare NativeStrokeCap = "square"

type NativeStrokeJoin string

const NativeStrokeJoinRound NativeStrokeJoin = "round"
const NativeStrokeJoinBevel NativeStrokeJoin = "bevel"
const NativeStrokeJoinMiter NativeStrokeJoin = "miter"

type NativeStrokeDash string

const NativeStrokeDashSolid NativeStrokeDash = "solid"

type NativeTextAlign string

const NativeTextAlignLeft NativeTextAlign = "left"
const NativeTextAlignCenter NativeTextAlign = "center"
const NativeTextAlignRight NativeTextAlign = "right"

type NativeTextWrap string

const NativeTextWrapSquare NativeTextWrap = "square"
const NativeTextWrapNone NativeTextWrap = "none"

type NativeTextVerticalAnchor string

const NativeTextVerticalAnchorTop NativeTextVerticalAnchor = "top"
const NativeTextVerticalAnchorCenter NativeTextVerticalAnchor = "center"
const NativeTextVerticalAnchorBottom NativeTextVerticalAnchor = "bottom"

type NativeAnimationEffect string

const NativeAnimationEffectFade NativeAnimationEffect = "fade"
const NativeAnimationEffectFlyIn NativeAnimationEffect = "flyIn"

type NativeTransitionType string

const NativeTransitionTypeFade NativeTransitionType = "fade"
const NativeTransitionTypePush NativeTransitionType = "push"
const NativeTransitionTypeWipe NativeTransitionType = "wipe"

type NativeDirection string

const NativeDirectionLeft NativeDirection = "left"
const NativeDirectionRight NativeDirection = "right"
const NativeDirectionUp NativeDirection = "up"
const NativeDirectionDown NativeDirection = "down"
