import { readFileSync } from 'node:fs'
import { createAgentSession } from '@injoffice/agent-tools'
import type { NativePptxDeck, NativeShapeElement } from '@injoffice/pptx-native'
import { describe, expect, it } from 'vitest'
import { createAuthoredDeckAgentAdapter, createNativePptxAgentAdapter, type AuthoredDeckAgentArtifact, type NativePptxAgentArtifact, type PptxNativeMutationRequest } from './pptx.js'

const authored = (): AuthoredDeckAgentArtifact => ({ kind: 'injoffice.deck-spec', artifactId: 'deck:1', spec: { id: 'quarterly', title: 'Quarterly update', slides: [{ id: 'opening', kind: 'title', title: 'Quarterly update', subtitle: 'Q3' }, { id: 'results', kind: 'bullets', title: 'Results', bullets: ['Revenue grew'] }] } })
const nativeRecord = JSON.parse(readFileSync(new URL('../../../go/officecompat/corpus/generated/expected/pptx-transitional-common.json', import.meta.url), 'utf8')) as { native: NativePptxDeck }
function nativeArtifact(): NativePptxAgentArtifact & { requests: PptxNativeMutationRequest[]; keys: string[] } { let deck = structuredClone(nativeRecord.native); const requests: PptxNativeMutationRequest[] = []; const keys: string[] = []; return { kind: 'injoffice.pptx-native', artifactId: 'native-pptx:1', requests, keys, async snapshot() { return { deck } }, async apply(request, options) { const next = structuredClone(deck); const mutation = request.operations[0]!; const target = next.slides[0]!.elements.find((element) => element.id === mutation.elementId)!; if (mutation.kind !== 'text.replace' || target.kind !== 'text') throw new Error('unexpected test mutation'); target.paragraphs = structuredClone(mutation.paragraphs); target.source!.fingerprintSha256 = 'c'.repeat(64); next.sourceRevision = `rev-${'d'.repeat(64)}`; deck = next; requests.push(structuredClone(request)); keys.push(options.idempotencyKey); return { snapshot: { deck }, receipt: { saved: true } } } } }

describe('PPTX agent sessions', () => {
  it('runs authored DeckSpec editing, wire preview, QC, commit, and verify', async () => { const input = authored(); const session = await createAgentSession({ artifact: input, actor: { id: 'agent-1', kind: 'agent' }, adapter: createAuthoredDeckAgentAdapter() }); expect((await session.capabilities()).capabilities.some(({ name }) => name === 'pptx.authored.slide.update')).toBe(true); await session.inspect({ maxItems: 5, maxBytes: 20_000 }); await session.read({ maxItems: 2, maxBytes: 20_000 }); const change = await session.plan([{ name: 'pptx.authored.slide.update', input: { slideId: 'results', patch: { bullets: ['Revenue grew', 'Margin improved'] } } }]); expect((await change.validate()).valid).toBe(true); expect((await change.preview()).data).toHaveProperty('wire'); await change.diff(); const committed = await change.commit({ idempotencyKey: 'deck-save-1' }); expect(committed.verification.verified).toBe(true); expect(session.artifact.spec.slides[1]?.bullets).toHaveLength(2) })
  it('runs source-anchored native PPTX text replacement through a host', async () => { const artifact = nativeArtifact(); const target = nativeRecord.native.slides[0]!.elements.find((element) => element.kind === 'text' && element.source)!; const session = await createAgentSession({ artifact, actor: { id: 'agent-1', kind: 'agent' }, adapter: createNativePptxAgentAdapter(), confirmDestructive: () => true }); expect((await session.capabilities()).capabilities.some(({ name }) => name === 'pptx.native.text.replace')).toBe(true); await session.inspect({ maxItems: 5, maxBytes: 20_000 }); await session.read({ query: { elementId: target.id }, maxItems: 2, maxBytes: 20_000 }); const change = await session.plan([{ name: 'pptx.native.text.replace', input: { elementId: target.id, text: 'Agent-native' } }]); expect((await change.validate()).valid).toBe(true); expect((await change.preview()).data).toMatchObject({ mode: 'validated-request' }); await change.diff(); const committed = await change.commit({ idempotencyKey: 'pptx-save-1', confirmation: true }); expect(artifact.keys).toEqual(['pptx-save-1']); expect(committed.verification.verified).toBe(true) })
  it('preserves the current native AutoShape fill when fill is omitted', async () => { const artifact = nativeArtifact(); const target = nativeRecord.native.slides[0]!.elements.find((element): element is NativeShapeElement => element.kind === 'shape' && Boolean(element.fill))!; const session = await createAgentSession({ artifact, actor: { id: 'agent-1', kind: 'agent' }, adapter: createNativePptxAgentAdapter() }); const change = await session.plan([{ name: 'pptx.native.autoshape.update', input: { elementId: target.id, preset: target.preset === 'rect' ? 'ellipse' : 'rect' } }]); expect((await change.validate()).valid).toBe(true); const preview = await change.preview(); expect(preview.evidence[0]?.data).toMatchObject({ operations: [{ autoShape: { fill: target.fill } }] }) })
  it('refuses malformed authored and native inputs before host apply', async () => { const a = authored(); const authoredSession = await createAgentSession({ artifact: a, actor: { id: 'agent-1', kind: 'agent' }, adapter: createAuthoredDeckAgentAdapter() }); const badAuthored = await authoredSession.plan([{ name: 'pptx.authored.slide.move', input: { slideId: 'missing', toIndex: -1 } }]); expect((await badAuthored.validate()).valid).toBe(false); const n = nativeArtifact(); const nativeSession = await createAgentSession({ artifact: n, actor: { id: 'agent-1', kind: 'agent' }, adapter: createNativePptxAgentAdapter() }); const badNative = await nativeSession.plan([{ name: 'pptx.native.text.replace', input: { elementId: 7, text: 'x' } }]); expect((await badNative.validate()).valid).toBe(false); expect(n.requests).toHaveLength(0) })
})
