import { auditDeck, compileDeckToWire, type DeckSpec, type DeckTheme, type SlideSpec } from '@injoffice/slides/authoring'
import { PPTX_NATIVE_RESOURCE_LIMITS, validateNativePptx, type NativeElement, type NativeParagraph, type NativePptxDeck, type NativeShapeElement, type NativeTransform } from '@injoffice/pptx-native'
import type { AgentArtifactAdapter, AgentArtifactIdentity, AgentCapability, AgentIssue, AgentOperation, JsonValue } from '@injoffice/agent-tools'
import { assertFresh, boundedObject, cursorOffset, errorIssue, fingerprintJSON, toJson } from './hash.js'

export interface AuthoredDeckAgentArtifact { readonly kind: 'injoffice.deck-spec'; readonly artifactId: string; readonly spec: DeckSpec }
type AuthoredResult = { spec?: DeckSpec; issues: AgentIssue[] }
const AUTHORED_CAPABILITIES: readonly AgentCapability[] = [
  ['pptx.authored.slide.insert', 'Insert one complete authored slide with a caller-supplied stable id.', false, { index: { type: 'integer', minimum: 0 }, slide: { type: 'object' } }, ['index', 'slide']],
  ['pptx.authored.slide.update', 'Patch one authored slide while preserving its stable id.', false, { slideId: { type: 'string' }, patch: { type: 'object' } }, ['slideId', 'patch']],
  ['pptx.authored.slide.remove', 'Remove one authored slide.', true, { slideId: { type: 'string' } }, ['slideId']],
  ['pptx.authored.slide.move', 'Move one authored slide to an absolute zero-based index.', false, { slideId: { type: 'string' }, toIndex: { type: 'integer', minimum: 0 } }, ['slideId', 'toIndex']],
  ['pptx.authored.deck.update', 'Update the authored deck title or theme.', false, { title: { type: 'string' }, theme: {} }, []],
].map(([name, description, destructive, properties, required]) => ({ name, description, destructive, requiresConfirmation: destructive, inputSchema: { type: 'object', properties, required, additionalProperties: false }, metadata: { execution: 'local', source: 'DeckSpec' } } as AgentCapability))

async function authoredIdentity(artifact: AuthoredDeckAgentArtifact): Promise<AgentArtifactIdentity> { const fingerprint = await fingerprintJSON(artifact.spec); return { artifactId: artifact.artifactId, format: 'pptx', mediaType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation', revision: fingerprint, fingerprint } }
function plain(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value) && Object.getPrototypeOf(value) === Object.prototype }
function validateDeck(spec: DeckSpec): AgentIssue[] { const issues: AgentIssue[] = []; if (!plain(spec) || typeof spec.id !== 'string' || typeof spec.title !== 'string' || !Array.isArray(spec.slides) || !spec.slides.length) return [{ severity: 'refusal', code: 'INVALID_DECK', message: 'DeckSpec requires id, title, and at least one slide' }]; const ids = new Set<string>(); for (const slide of spec.slides) { if (!plain(slide) || typeof slide.id !== 'string' || !slide.id || ids.has(slide.id) || !['title', 'section', 'bullets', 'two-col', 'quote', 'closing'].includes(slide.kind)) issues.push({ severity: 'refusal', code: 'INVALID_SLIDE', message: 'slides require unique ids and supported authored kinds' }); ids.add(slide.id) }; try { compileDeckToWire(spec) } catch (error) { issues.push({ ...errorIssue(error), severity: 'refusal' }) }; return issues }
function applyAuthored(source: DeckSpec, operations: readonly AgentOperation[]): AuthoredResult {
  const spec = structuredClone(source); const issues: AgentIssue[] = []
  for (const operation of operations) {
    const input = operation.input
    const allowed = operation.name === 'pptx.authored.slide.insert' ? ['index', 'slide'] : operation.name === 'pptx.authored.slide.update' ? ['slideId', 'patch'] : operation.name === 'pptx.authored.slide.remove' ? ['slideId'] : operation.name === 'pptx.authored.slide.move' ? ['slideId', 'toIndex'] : operation.name === 'pptx.authored.deck.update' ? ['title', 'theme'] : []
    const extra = Object.keys(input).find((key) => !allowed.includes(key)); if (extra) { issues.push({ severity: 'refusal', code: 'UNKNOWN_FIELD', operationId: operation.operationId, path: `/input/${extra}`, message: `unknown input field ${extra}` }); continue }
    switch (operation.name) {
      case 'pptx.authored.slide.insert': { const index = input.index; const slide = input.slide as unknown; if (!Number.isSafeInteger(index) || (index as number) < 0 || (index as number) > spec.slides.length || !plain(slide) || typeof slide.id !== 'string' || spec.slides.some((item) => item.id === slide.id)) issues.push({ severity: 'refusal', code: 'INVALID_INSERT', operationId: operation.operationId, message: 'insert requires an in-range index and new stable slide id' }); else spec.slides.splice(index as number, 0, structuredClone(slide) as unknown as SlideSpec); break }
      case 'pptx.authored.slide.update': { const at = spec.slides.findIndex((slide) => slide.id === input.slideId); if (at < 0 || !plain(input.patch) || Object.hasOwn(input.patch, 'id')) issues.push({ severity: 'refusal', code: 'INVALID_UPDATE', operationId: operation.operationId, message: 'update requires an existing slideId and patch without id' }); else spec.slides[at] = { ...spec.slides[at]!, ...structuredClone(input.patch) as Partial<SlideSpec>, id: input.slideId as string }; break }
      case 'pptx.authored.slide.remove': { const at = spec.slides.findIndex((slide) => slide.id === input.slideId); if (at < 0 || spec.slides.length === 1) issues.push({ severity: 'refusal', code: 'INVALID_REMOVE', operationId: operation.operationId, message: 'cannot remove a missing or only slide' }); else spec.slides.splice(at, 1); break }
      case 'pptx.authored.slide.move': { const at = spec.slides.findIndex((slide) => slide.id === input.slideId); const to = input.toIndex; if (at < 0 || !Number.isSafeInteger(to) || (to as number) < 0 || (to as number) >= spec.slides.length) issues.push({ severity: 'refusal', code: 'INVALID_MOVE', operationId: operation.operationId, message: 'move requires an existing slide and in-range destination' }); else { const [slide] = spec.slides.splice(at, 1); spec.slides.splice(to as number, 0, slide!) }; break }
      case 'pptx.authored.deck.update': { if (input.title !== undefined) { if (typeof input.title !== 'string') issues.push({ severity: 'refusal', code: 'INVALID_TITLE', operationId: operation.operationId, message: 'title must be a string' }); else spec.title = input.title }; if (input.theme === null) delete spec.theme; else if (input.theme !== undefined) spec.theme = structuredClone(input.theme) as string | DeckTheme; break }
      default: issues.push({ severity: 'refusal', code: 'UNSUPPORTED_OPERATION', operationId: operation.operationId, message: `unsupported authored PPTX operation ${operation.name}` })
    }
  }
  issues.push(...validateDeck(spec)); return issues.length ? { issues } : { spec, issues }
}

export function createAuthoredDeckAgentAdapter(): AgentArtifactAdapter<AuthoredDeckAgentArtifact> {
  return {
    id: 'injoffice.pptx.authored-deck-v1', format: 'pptx',
    supports(value): value is AuthoredDeckAgentArtifact { return typeof value === 'object' && value !== null && (value as Partial<AuthoredDeckAgentArtifact>).kind === 'injoffice.deck-spec' && typeof (value as Partial<AuthoredDeckAgentArtifact>).artifactId === 'string' && plain((value as Partial<AuthoredDeckAgentArtifact>).spec) },
    async identity({ artifact }) { return authoredIdentity(artifact) }, async capabilities() { return structuredClone(AUTHORED_CAPABILITIES) },
    async inspect({ artifact, cursor, maxItems, maxBytes }) { const qc = auditDeck(artifact.spec); return boundedObject({ id: artifact.spec.id, title: artifact.spec.title, theme: toJson(artifact.spec.theme ?? null), slideCount: artifact.spec.slides.length, qc: toJson(qc) }, 'slides', artifact.spec.slides.map(({ id, kind, title }) => ({ id, kind, title: title ?? null })), cursorOffset(cursor), maxItems, maxBytes) },
    async read({ artifact, query, cursor, maxItems, maxBytes }) { const slideId = query?.slideId; const items = typeof slideId === 'string' ? artifact.spec.slides.filter((slide) => slide.id === slideId) : artifact.spec.slides; if (typeof slideId === 'string' && !items.length) throw new Error('requested authored slide does not exist'); return boundedObject({}, 'slides', items, cursorOffset(cursor), maxItems, maxBytes) },
    async validate(request) { const issues: AgentIssue[] = []; try { assertFresh(await authoredIdentity(request.artifact), request.sourceIdentity) } catch (error) { issues.push({ ...errorIssue(error), severity: 'error' }) }; issues.push(...applyAuthored(request.artifact.spec, request.changeSet.operations).issues); return issues },
    async preview(request) { assertFresh(await authoredIdentity(request.artifact), request.sourceIdentity); const result = applyAuthored(request.artifact.spec, request.changeSet.operations); if (!result.spec) return { data: toJson({ mode: 'refused' }), issues: result.issues, evidence: [] }; const qc = auditDeck(result.spec); return { data: toJson({ spec: result.spec, wire: compileDeckToWire(result.spec), qc }), issues: qc.map((item) => ({ severity: 'warning', code: `LAYOUT_${item.kind.toUpperCase().replaceAll('-', '_')}`, path: `/slides/${item.slideIndex}`, message: item.message })), evidence: [{ kind: 'pptx.authored-wire', data: { slideCount: result.spec.slides.length } }] } },
    async diff(request) { const result = applyAuthored(request.artifact.spec, request.changeSet.operations); return { data: { beforeRevision: request.sourceIdentity.revision, afterRevision: result.spec ? await fingerprintJSON(result.spec) : null, operations: request.changeSet.operations.map(({ operationId, name }) => ({ operationId, name })), qcBefore: toJson(auditDeck(request.artifact.spec)), qcAfter: toJson(result.spec ? auditDeck(result.spec) : []) }, issues: result.issues, evidence: [] } },
    async commit(request) { assertFresh(await authoredIdentity(request.artifact), request.sourceIdentity); const result = applyAuthored(request.artifact.spec, request.changeSet.operations); if (!result.spec) throw new Error(result.issues.map((issue) => issue.message).join('; ')); const artifact = { kind: 'injoffice.deck-spec' as const, artifactId: request.artifact.artifactId, spec: result.spec }; const qc = auditDeck(result.spec); return { artifact, identity: await authoredIdentity(artifact), data: { slideCount: result.spec.slides.length, qc: toJson(qc) }, evidence: [{ kind: 'pptx.authored-wire', data: toJson(compileDeckToWire(result.spec)) }] } },
    async verify(request) { const issues = validateDeck(request.artifact.spec); const qc = auditDeck(request.artifact.spec); const checks = [{ name: 'deck-contract-and-wire', passed: !issues.length }, { name: 'deterministic-layout-qc', passed: !qc.length, evidence: [{ kind: 'pptx.layout-qc', data: toJson(qc) }] }]; return { verified: checks.every((check) => check.passed), checks, issues: [...issues, ...qc.map((item) => ({ severity: 'error' as const, code: `LAYOUT_${item.kind.toUpperCase().replaceAll('-', '_')}`, message: item.message }))] } },
  }
}

export interface PptxNativeExactTextRun { text: string; bold: boolean; italic: boolean; fontSizeHundredthPt: number; color: string; fontFamily: string }
export interface PptxNativeExactParagraph { runs: PptxNativeExactTextRun[]; align: 'left' | 'center' | 'right'; level: number; bullet: false }
export interface PptxNativeMutationRequest { expectedSourceRevision: string; operations: Array<{ operationId: string; kind: 'text.replace'; elementId: string; expectedFingerprintSha256: string; paragraphs: PptxNativeExactParagraph[] } | { operationId: string; kind: 'autoshape.update'; elementId: string; expectedFingerprintSha256: string; autoShape: { transform: NativeTransform; preset: 'rect' | 'ellipse' | 'triangle' | 'diamond'; fill?: string; stroke?: { color: string; widthEmu: number; cap: 'flat' | 'round' | 'square'; join: 'round' | 'bevel' | 'miter'; dash: 'solid'; miterLimit?: number } } }> }
export interface NativePptxAgentSnapshot { deck: NativePptxDeck }
export interface NativePptxAgentArtifact {
  readonly kind: 'injoffice.pptx-native'; readonly artifactId: string
  snapshot(options?: { signal?: AbortSignal }): Promise<NativePptxAgentSnapshot>
  apply(request: PptxNativeMutationRequest, options: { idempotencyKey: string; signal?: AbortSignal }): Promise<{ snapshot: NativePptxAgentSnapshot; receipt?: JsonValue; deduplicated?: boolean }>
  preview?(request: PptxNativeMutationRequest, options?: { signal?: AbortSignal }): Promise<NativePptxAgentSnapshot>
}
const NATIVE_CAPABILITIES: readonly AgentCapability[] = [
  { name: 'pptx.native.text.replace', description: 'Replace the first text run while preserving exact paragraph/run formatting metadata.', destructive: true, requiresConfirmation: true, inputSchema: { type: 'object', properties: { elementId: { type: 'string' }, text: { type: 'string' } }, required: ['elementId', 'text'], additionalProperties: false }, metadata: { execution: 'host', wholeFileWrite: true } },
  { name: 'pptx.native.autoshape.update', description: 'Update an exact parsed rectangle, ellipse, triangle, or diamond preset and optional fill.', destructive: true, requiresConfirmation: true, inputSchema: { type: 'object', properties: { elementId: { type: 'string' }, preset: { enum: ['rect', 'ellipse', 'triangle', 'diamond'] }, fill: { type: ['string', 'null'], pattern: '^[0-9A-F]{6}$' } }, required: ['elementId', 'preset'], additionalProperties: false }, metadata: { execution: 'host', wholeFileWrite: true } },
]
function elements(deck: NativePptxDeck): NativeElement[] { const output: NativeElement[] = []; const visit = (item: NativeElement) => { output.push(item); if (item.kind === 'group') item.children.forEach(visit) }; deck.slides.forEach((slide) => slide.elements.forEach(visit)); return output }
async function nativeIdentity(artifact: NativePptxAgentArtifact, deck: NativePptxDeck): Promise<AgentArtifactIdentity> { const fingerprint = deck.sourceRevision ?? await fingerprintJSON(deck); return { artifactId: artifact.artifactId, format: 'pptx', mediaType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation', revision: fingerprint, fingerprint } }
async function nativeSnapshot(artifact: NativePptxAgentArtifact, signal?: AbortSignal) { const current = await artifact.snapshot({ signal }); const checked = validateNativePptx(current.deck); if (!checked.ok) throw new Error(`invalid native PPTX snapshot: ${checked.issues[0]?.message ?? 'unknown error'}`); return { deck: structuredClone(checked.value) } }
function exactParagraphs(value: { paragraphs: NativeParagraph[] }): PptxNativeExactParagraph[] | undefined { const paragraphs: PptxNativeExactParagraph[] = []; for (const paragraph of value.paragraphs) { if (paragraph.bullet === true) return undefined; const runs: PptxNativeExactTextRun[] = []; for (const run of paragraph.runs) { if (run.bold === undefined || run.italic === undefined || run.fontSizeHundredthPt === undefined || run.color === undefined || !/^[0-9A-F]{6}$/.test(run.color) || run.fontFamily === undefined || !run.fontFamily) return undefined; runs.push({ text: run.text, bold: run.bold, italic: run.italic, fontSizeHundredthPt: run.fontSizeHundredthPt, color: run.color, fontFamily: run.fontFamily }) }; paragraphs.push({ runs, align: paragraph.align ?? 'left', level: paragraph.level ?? 0, bullet: false }) }; return paragraphs }
function nativeRequest(deck: NativePptxDeck, operations: readonly AgentOperation[]): { value?: PptxNativeMutationRequest; issues: AgentIssue[] } {
  const issues: AgentIssue[] = []; const result: PptxNativeMutationRequest = { expectedSourceRevision: deck.sourceRevision ?? '', operations: [] }; const index = new Map(elements(deck).map((item) => [item.id, item])); if (deck.origin !== 'parsed' || !deck.sourceRevision) issues.push({ severity: 'refusal', code: 'UNSUPPORTED_SOURCE', message: 'native PPTX mutation requires a parsed exact source revision' })
  for (const operation of operations) { const allowed = operation.name === 'pptx.native.text.replace' ? ['elementId', 'text'] : operation.name === 'pptx.native.autoshape.update' ? ['elementId', 'preset', 'fill'] : []; const extra = Object.keys(operation.input).find((key) => !allowed.includes(key)); if (extra) { issues.push({ severity: 'refusal', code: 'UNKNOWN_FIELD', operationId: operation.operationId, path: `/input/${extra}`, message: `unknown input field ${extra}` }); continue }; const rawElementId = operation.input.elementId; const elementId = typeof rawElementId === 'string' ? rawElementId : ''; const target = elementId ? index.get(elementId) : undefined; if (!target?.source || target.compatibility.status === 'refused') { issues.push({ severity: 'refusal', code: 'UNSUPPORTED_TARGET', operationId: operation.operationId, message: 'target is absent, unanchored, or refused' }); continue }
    if (operation.name === 'pptx.native.text.replace') { const text = operation.input.text; const paragraphs = target.kind === 'text' || target.kind === 'shape' ? exactParagraphs(target) : undefined; if (typeof text !== 'string' || text.length > PPTX_NATIVE_RESOURCE_LIMITS.maxTextCodeUnits || /[\t\r\n]/.test(text) || !paragraphs?.[0]?.runs[0] || text === paragraphs[0].runs[0].text) issues.push({ severity: 'refusal', code: 'INVALID_TEXT_REPLACE', operationId: operation.operationId, message: 'target requires exact text metadata and a changed, bounded single-line replacement string' }); else { paragraphs[0].runs[0].text = text; result.operations.push({ operationId: operation.operationId, kind: 'text.replace', elementId, expectedFingerprintSha256: target.source.fingerprintSha256, paragraphs }) } }
    else if (operation.name === 'pptx.native.autoshape.update') {
      const preset = operation.input.preset; const fill = operation.input.fill; const shape = target.kind === 'shape' ? target as NativeShapeElement : undefined
      const resolvedFill = fill === undefined ? shape?.fill : fill
      if (!shape?.preset || !['rect', 'ellipse', 'triangle', 'diamond'].includes(preset as string) || resolvedFill !== undefined && resolvedFill !== null && (typeof resolvedFill !== 'string' || !/^[0-9A-F]{6}$/.test(resolvedFill)) || preset === shape.preset && (resolvedFill ?? null) === (shape.fill ?? null)) issues.push({ severity: 'refusal', code: 'INVALID_AUTOSHAPE_UPDATE', operationId: operation.operationId, message: 'target must be an exact supported AutoShape with a changed preset/fill and canonical color' })
      else result.operations.push({ operationId: operation.operationId, kind: 'autoshape.update', elementId, expectedFingerprintSha256: target.source.fingerprintSha256, autoShape: { transform: structuredClone(shape.transform), preset: preset as 'rect', ...(typeof resolvedFill === 'string' ? { fill: resolvedFill } : {}), ...(shape.stroke ? { stroke: { color: shape.stroke.color, widthEmu: shape.stroke.widthEmu, cap: shape.stroke.cap ?? 'flat', join: shape.stroke.join ?? 'round', dash: 'solid', ...(shape.stroke.miterLimit === undefined ? {} : { miterLimit: shape.stroke.miterLimit }) } } : {}) } })
    }
    else issues.push({ severity: 'refusal', code: 'UNSUPPORTED_OPERATION', operationId: operation.operationId, message: `unsupported native PPTX operation ${operation.name}` })
  }
  return issues.length ? { issues } : { value: result, issues }
}
function nativeReadback(deck: NativePptxDeck, operation: AgentOperation): boolean { const target = elements(deck).find((item) => item.id === operation.input.elementId); if (operation.name === 'pptx.native.text.replace') return (target?.kind === 'text' || target?.kind === 'shape') && target.paragraphs[0]?.runs[0]?.text === operation.input.text; if (operation.name === 'pptx.native.autoshape.update') return target?.kind === 'shape' && target.preset === operation.input.preset && (!Object.hasOwn(operation.input, 'fill') || (target.fill ?? null) === (operation.input.fill ?? null)); return false }

export function createNativePptxAgentAdapter(): AgentArtifactAdapter<NativePptxAgentArtifact> {
  return {
    id: 'injoffice.pptx.native-v1', format: 'pptx',
    supports(value): value is NativePptxAgentArtifact { return typeof value === 'object' && value !== null && (value as Partial<NativePptxAgentArtifact>).kind === 'injoffice.pptx-native' && typeof (value as Partial<NativePptxAgentArtifact>).artifactId === 'string' && typeof (value as Partial<NativePptxAgentArtifact>).snapshot === 'function' && typeof (value as Partial<NativePptxAgentArtifact>).apply === 'function' },
    async identity({ artifact, signal }) { const current = await nativeSnapshot(artifact, signal); return nativeIdentity(artifact, current.deck) }, async capabilities() { return structuredClone(NATIVE_CAPABILITIES) },
    async inspect({ artifact, cursor, maxItems, maxBytes, signal }) { const { deck } = await nativeSnapshot(artifact, signal); return boundedObject({ documentId: deck.documentId, origin: deck.origin, compatibility: toJson(deck.compatibility), slideCount: deck.slides.length }, 'slides', deck.slides.map((slide) => ({ id: slide.id, elementCount: slide.elements.length, compatibility: slide.compatibility })), cursorOffset(cursor), maxItems, maxBytes) },
    async read({ artifact, query, cursor, maxItems, maxBytes, signal }) { const { deck } = await nativeSnapshot(artifact, signal); const elementId = query?.elementId; const items = typeof elementId === 'string' ? elements(deck).filter((item) => item.id === elementId) : elements(deck); if (typeof elementId === 'string' && !items.length) throw new Error('requested native PPTX element does not exist'); return boundedObject({}, 'elements', items, cursorOffset(cursor), maxItems, maxBytes) },
    async validate(request) { const { deck } = await nativeSnapshot(request.artifact, request.signal); const issues: AgentIssue[] = []; try { assertFresh(await nativeIdentity(request.artifact, deck), request.sourceIdentity) } catch (error) { issues.push({ ...errorIssue(error), severity: 'error' }) }; issues.push(...nativeRequest(deck, request.changeSet.operations).issues); return issues },
    async preview(request) { const { deck } = await nativeSnapshot(request.artifact, request.signal); assertFresh(await nativeIdentity(request.artifact, deck), request.sourceIdentity); const built = nativeRequest(deck, request.changeSet.operations); if (!built.value) return { data: toJson({ mode: 'refused' }), issues: built.issues, evidence: [] }; if (!request.artifact.preview) return { data: toJson({ mode: 'validated-request', operationCount: built.value.operations.length }), issues: [], evidence: [{ kind: 'pptx.native-mutation-request', data: toJson(built.value) }] }; const next = await request.artifact.preview(built.value, { signal: request.signal }); const checked = validateNativePptx(next.deck); if (!checked.ok) throw new Error(`native PPTX preview returned invalid output: ${checked.issues[0]?.message ?? 'unknown error'}`); const passed = request.changeSet.operations.every((operation) => nativeReadback(checked.value, operation)); return { data: toJson({ mode: 'native-host', operationCount: built.value.operations.length, readbackPassed: passed, resultingRevision: checked.value.sourceRevision ?? null }), issues: passed ? [] : [{ severity: 'error', code: 'PREVIEW_MISMATCH', message: 'native PPTX preview readback failed' }], evidence: [] } },
    async diff(request) { const { deck } = await nativeSnapshot(request.artifact, request.signal); const built = nativeRequest(deck, request.changeSet.operations); return { data: { operations: built.value ? toJson(built.value.operations.map((operation) => ({ operationId: operation.operationId, kind: operation.kind, elementId: operation.elementId }))) : [] }, issues: built.issues, evidence: [] } },
    async commit(request) { const { deck } = await nativeSnapshot(request.artifact, request.signal); assertFresh(await nativeIdentity(request.artifact, deck), request.sourceIdentity); const built = nativeRequest(deck, request.changeSet.operations); if (!built.value) throw new Error(built.issues.map((issue) => issue.message).join('; ')); const applied = await request.artifact.apply(built.value, { idempotencyKey: request.idempotencyKey, signal: request.signal }); const checked = validateNativePptx(applied.snapshot.deck); if (!checked.ok) throw new Error(`native PPTX host returned invalid output: ${checked.issues[0]?.message ?? 'unknown error'}`); return { artifact: request.artifact, identity: await nativeIdentity(request.artifact, checked.value), data: { operationCount: built.value.operations.length, ...(applied.receipt === undefined ? {} : { hostReceipt: applied.receipt }) }, evidence: [{ kind: 'pptx.native-commit', data: { operationIds: built.value.operations.map((item) => item.operationId) } }], deduplicated: applied.deduplicated } },
    async verify(request) { if (request.stage === 'planned') { const issues = await this.validate(request); const passed = !issues.some((issue) => issue.severity !== 'warning'); return { verified: passed, checks: [{ name: 'native-pptx-plan', passed }], issues } }; const { deck } = await nativeSnapshot(request.artifact, request.signal); const checks = request.changeSet.operations.map((operation) => ({ name: `operation:${operation.operationId}`, passed: nativeReadback(deck, operation) })); const issues = checks.filter((check) => !check.passed).map((check) => ({ severity: 'error' as const, code: 'VERIFY_FAILED', message: `${check.name} was not observed in the fresh native projection` })); return { verified: checks.length > 0 && checks.every((check) => check.passed), checks, issues } },
  }
}
