// Deck model for @injoffice/slides.
//
// Same contract philosophy as ChartSpec/PivotSpec: DeckSpec is plain JSON —
// what an agent emits and what persists. Production Office rendering compiles
// this contract through @injoffice/pptx-authored into pptx-native/v1. The
// React/Konva views are retained as legacy editing/preview surfaces only.

/** One deck. */
export interface DeckSpec {
  id: string
  title: string
  /** Theme id (built-in) or a full custom theme object. */
  theme?: string | DeckTheme
  slides: SlideSpec[]
}

export type SlideKind = 'title' | 'section' | 'bullets' | 'two-col' | 'quote' | 'closing'

/** One slide. Fields are per-kind; unknown extras are preserved. */
export interface SlideSpec {
  id: string
  kind: SlideKind
  /** Small label above the title (kicker/eyebrow). */
  eyebrow?: string
  title?: string
  subtitle?: string
  /** bullets / two-col: list items. Plain text with **bold** and *italic*. */
  bullets?: string[]
  /** two-col: right column items (bullets is the left column). */
  bulletsRight?: string[]
  /** Column headings for two-col. */
  colTitles?: [string, string]
  /** quote: the quoted line; subtitle carries the attribution. */
  quote?: string
  /** Freeform paragraph under the title (title/section/closing). */
  body?: string
  /** Speaker notes — never rendered on the slide. */
  notes?: string
  /** Per-shape position/size overrides from the Canvas view's drag/resize
   *  editor (S8 persistence — see compile.ts), keyed by the shape's STABLE
   *  ROLE within this slide kind ('title', 'subtitle', 'bullets', ... — see
   *  each compileXxx function in compile.ts for the exact keys a given
   *  kind produces), not by array index (which shifts whenever content
   *  changes, e.g. adding an eyebrow inserts a new shape ahead of
   *  everything else). Applied ON TOP of the compiler's own default
   *  layout for that role. Any field left out of one override falls back
   *  to the compiler's default for it. HTML-first still holds: DeckView
   *  (the DOM renderer) has no absolute positioning at all and simply
   *  never reads this — it's Canvas-view-only. An override whose key no
   *  longer matches any compiled shape (its role's content was cleared,
   *  so the compiler never produces that shape at all) is silently
   *  inert, not an error — a host MAY prune stale keys but doesn't have
   *  to; nothing depends on this map being minimal. */
  shapeOverrides?: Record<string, ShapePositionOverride>
  /** Per-shape entrance animations (S11), keyed the SAME way as
   *  shapeOverrides — by the shape's stable role within this slide kind,
   *  not array index. Optional and additive: a slide with no
   *  shapeAnimations compiles and renders exactly as before S11. */
  shapeAnimations?: Record<string, ShapeAnimationSpec>
  /** This slide's entrance transition (S11) — how it transitions IN when
   *  advancing to it from the previous slide. Optional; omitted = no
   *  transition (PowerPoint's own default: an instant cut). */
  transition?: SlideTransitionSpec
  /** S12 diagram slice: an optional simple diagram (process flow / org
   *  chart), laid out and compiled as a COMPOSITION of existing primitives —
   *  roundRect/rect boxes + KindLine connectors, positioned by this
   *  package's own layout code (diagram.ts) — NOT real OOXML SmartArt
   *  (the `dgm` namespace's own separate data/layout/quickstyle/colors XML
   *  parts, generated by PowerPoint's layout engine). That real format is a
   *  large, separate undertaking judged not worth it for the visual outcome
   *  most users actually want; this gets the same VISUAL result (boxes and
   *  arrows PowerPoint opens and lets you edit like any other shape) without
   *  it, at the cost of not being a "real SmartArt object" a user could
   *  swap to a different SmartArt layout via PowerPoint's own SmartArt UI.
   *  Additive and independent of `kind` — any slide kind may carry one;
   *  DeckCanvasView renders it for free (it's just more WireShapes) since it
   *  compiles to the same shape primitives every other slide kind uses.
   *  DeckView (the HTML/DOM renderer) does NOT render this field — see
   *  compile.ts's compileDiagramShapes for exactly what it produces. */
  diagram?: DiagramSpec
}

/** One of go/pptxpatch's two supported entrance effects (S11) —
 *  deliberately narrow, see go/pptxpatch's AnimEffect doc comment for why
 *  these two and not more. */
export type EnterAnimation = 'fade' | 'flyIn'

/** A side-of-slide direction: for 'flyIn', which edge the shape flies in
 *  FROM; for a push/wipe SlideTransitionSpec, which edge the incoming slide
 *  arrives FROM. */
export type AnimDirection = 'left' | 'right' | 'top' | 'bottom'

/** One shape's entrance animation override — see SlideSpec.shapeAnimations. */
export interface ShapeAnimationSpec {
  enter: EnterAnimation
  /** 'flyIn' only; default 'bottom' (the most common PowerPoint entrance
   *  direction) when omitted. Ignored for 'fade'. */
  direction?: AnimDirection
  /** Milliseconds before this shape's entrance starts, relative to the
   *  slide loading — lets a host stagger several shapes' entrances.
   *  Default 0 (plays immediately, no click required). */
  delayMs?: number
  /** Entrance duration in milliseconds. Default 500. */
  durationMs?: number
  /** 'flyIn' only: how far off-slide the shape starts, as a fraction
   *  (0..1) of slide width (left/right) or height (top/bottom). Default
   *  0.25. Ignored for 'fade'. */
  distance?: number
}

/** go/pptxpatch's two supported slide-transition types (S11) — see
 *  go/pptxpatch's TransitionType doc comment. */
export type SlideTransitionKind = 'fade' | 'push' | 'wipe'

/** This slide's entrance transition — see SlideSpec.transition. */
export interface SlideTransitionSpec {
  kind: SlideTransitionKind
  /** 'push'/'wipe' only: which edge the incoming slide arrives from.
   *  Default 'left' (OOXML's own schema default) when omitted. Ignored for
   *  'fade'. */
  direction?: AnimDirection
}

/** See SlideSpec.diagram. 'process': a left-to-right row of boxes joined by
 *  directional arrows. 'orgChart': a top-down tree of boxes joined by plain
 *  (arrowless) connector lines, parent bottom-center to each child's
 *  top-center. Both computed by diagram.ts, not stored pre-laid-out — the
 *  same "spec is the contract, layout is derived" split as every other
 *  compileXxx in compile.ts. */
export type DiagramSpec = { type: 'process'; steps: string[] } | { type: 'orgChart'; root: OrgChartNode }

/** One node of an org-chart DiagramSpec. A tree, not a flat list — children
 *  are this node's direct reports. */
export interface OrgChartNode {
  label: string
  children?: OrgChartNode[]
}

/** EMU position/size override for one compiled shape — see SlideSpec.
 *  shapeOverrides. Every field optional: only the ones a drag (x/y) or
 *  resize (x/y/cx/cy) actually changed need to be present. */
export interface ShapePositionOverride {
  x?: number
  y?: number
  cx?: number
  cy?: number
}

/** Theme tokens. Every field has a default; hosts override what they brand. */
export interface DeckTheme {
  id: string
  /** Page background. */
  background: string
  /** Panel/backdrop for quotes and code. */
  surface: string
  ink: string
  muted: string
  accent: string
  /** Display face stack (titles). */
  displayFont: string
  /** Body face stack. */
  bodyFont: string
  /** Eyebrow/utility face stack (mono recommended). */
  monoFont: string
}
