import {describe,it,expect} from 'vitest'
import {decodeNativeWorkbookObjectsV1,layoutNativeCachedChartV1,type NativeWorkbookObjectsV1} from './nativeObjectsPreviewV1'
const hash=`sha256:${'a'.repeat(64)}`
const fixture=():NativeWorkbookObjectsV1=>({protocol:'injoffice.xlsx.preview-objects',version:1,package_sha256:hash,tables:[],charts:[{part:'xl/charts/chart1.xml',type:'col',series:[{name:'Saved',values:[1.25,-3],labels:[]}],warnings:['Saved cache may be stale']}]})
describe('native saved object previews',()=>{
 it('requires complete category associations and owns cached text',()=>{const input=fixture();input.charts[0]!.series[0]!.labels=['January',''];const output=decodeNativeWorkbookObjectsV1(input,hash);expect(output.charts[0]!.series[0]!.labels).toEqual(['January','']);output.charts[0]!.series[0]!.labels[0]='changed';expect(input.charts[0]!.series[0]!.labels[0]).toBe('January');input.charts[0]!.series[0]!.labels=['January'];expect(()=>decodeNativeWorkbookObjectsV1(input,hash)).toThrow()})
 it('rejects accessors without invoking them and refuses oversized paint workloads',()=>{let called=false;const input=fixture();Object.defineProperty(input,'charts',{get(){called=true;return []},enumerable:true});expect(()=>decodeNativeWorkbookObjectsV1(input,hash)).toThrow();expect(called).toBe(false);const chart=fixture().charts[0]!;chart.series=[{name:'A',values:Array(1024).fill(1),labels:[]},{name:'B',values:[1],labels:[]}];expect(layoutNativeCachedChartV1(chart)).toBeUndefined()})
 it('validates and owns a source-bound copy without editing source',()=>{const input=fixture(),output=decodeNativeWorkbookObjectsV1(input,hash);expect(output).toEqual(input);output.charts[0]!.series[0]!.values[0]=99;expect(input.charts[0]!.series[0]!.values[0]).toBe(1.25)})
 it('rejects stale, unknown, invalid and unbounded payloads',()=>{expect(()=>decodeNativeWorkbookObjectsV1(fixture(),`sha256:${'b'.repeat(64)}`)).toThrow();for(const modify of [(v:any)=>v.extra=1,(v:any)=>v.charts[0].series[0].values=[Infinity],(v:any)=>v.charts[0].series[0].values=Array(1025).fill(1),(v:any)=>v.charts[0].part='../x',(v:any)=>v.charts.push(v.charts[0])]){const v=fixture();modify(v);expect(()=>decodeNativeWorkbookObjectsV1(v,hash)).toThrow()}})
 it('lays out positive and negative saved values with explicit zero baseline',()=>{for(const type of ['col','bar'] as const){const chart=fixture().charts[0]!;chart.type=type;const result=layoutNativeCachedChartV1(chart)!;expect(result.minimum).toBe(-3);expect(result.maximum).toBe(1.25);expect(result.marks.map(m=>m.value)).toEqual([1.25,-3]);for(const mark of result.marks){expect(mark.x).toBeGreaterThanOrEqual(0);expect(mark.y).toBeGreaterThanOrEqual(0);expect(mark.x+mark.width).toBeLessThanOrEqual(1.000001);expect(mark.y+mark.height).toBeLessThanOrEqual(1.000001)}}})
 it('refuses unsupported data rather than fabricating it',()=>{const chart=fixture().charts[0]!;chart.type='unsupported';expect(layoutNativeCachedChartV1(chart)).toBeUndefined();chart.type='col';chart.series[0]!.values=[null];expect(layoutNativeCachedChartV1(chart)).toBeUndefined();chart.series[0]!.values=[-Number.MAX_VALUE,Number.MAX_VALUE];expect(layoutNativeCachedChartV1(chart)).toBeUndefined()})
})
