// Code generated by scripts/generate-xlsx-native-contract.mjs; DO NOT EDIT.
// Source: schemas/xlsx-native-v2.schema.json

export const XLSX_NATIVE_V2_SCHEMA_ID = "https://schemas.injoffice.dev/xlsx/native-v2.schema.json" as const
export const XLSX_NATIVE_V2_SCHEMA_SHA256 = "sha256:35297ab41a07d92fc705770dfdf10c717cde3400dde24e78955e0ce1bf4b017c" as const
export const XLSX_NATIVE_V2_PROTOCOL = "injoffice.xlsx.native" as const
export const XLSX_NATIVE_V2_VERSION = 2 as const
export const XLSX_NATIVE_V2_MEDIA_TYPE = "application/vnd.injoffice.xlsx-native.v2+json" as const
export const XLSX_NATIVE_V2_RESOURCE_LIMITS = {
  "maxJsonBytes": 134217728,
  "maxJsonDepth": 256,
  "maxJsonTokens": 4000000,
  "maxSheets": 1024,
  "maxRows": 1048576,
  "maxColumns": 16384,
  "maxCells": 1000000,
  "maxMergedRanges": 100000,
  "maxStyles": 100000,
  "maxInventory": 10000,
  "maxTextBytes": 33554432,
  "maxPartBytes": 67108864,
  "maxIssues": 100
} as const
export const XLSX_NATIVE_V2_UNSUPPORTED_CLASSIFICATIONS = {
  "CELL_ATTRIBUTES": {
    "capability": "cell-markup",
    "scope": "sheet",
    "impact": "cell"
  },
  "CELL_EXTENSIONS": {
    "capability": "extensions",
    "scope": "sheet",
    "impact": "cell"
  },
  "CELL_METADATA": {
    "capability": "cell-metadata",
    "scope": "sheet",
    "impact": "cell"
  },
  "OPAQUE_CELL_MARKUP": {
    "capability": "cell-markup",
    "scope": "sheet",
    "impact": "cell"
  },
  "RICH_CELL_STRING": {
    "capability": "rich-text",
    "scope": "sheet",
    "impact": "cell"
  },
  "FORMULA_ATTRIBUTES": {
    "capability": "formula-groups",
    "scope": "sheet",
    "impact": "cell"
  },
  "FORMULA_SHARED": {
    "capability": "formula-groups",
    "scope": "sheet",
    "impact": "cell"
  },
  "FORMULA_ARRAY": {
    "capability": "formula-groups",
    "scope": "sheet",
    "impact": "cell"
  },
  "FORMULA_DATATABLE": {
    "capability": "formula-groups",
    "scope": "sheet",
    "impact": "cell"
  },
  "FORMULA_GROUP_RANGE": {
    "capability": "formula-groups",
    "scope": "sheet",
    "impact": "range"
  },
  "SHEET_PROTECTION": {
    "capability": "protection",
    "scope": "sheet",
    "impact": "sheet",
    "refusalCode": "SHEET_PROTECTION"
  },
  "WORKSHEET_ATTRIBUTES": {
    "capability": "worksheet-features",
    "scope": "sheet",
    "impact": "sheet",
    "refusalCode": "UNSAFE_WORKSHEET_ATTRIBUTES"
  },
  "SHEET_DATA_ATTRIBUTES": {
    "capability": "worksheet-features",
    "scope": "sheet",
    "impact": "sheet",
    "refusalCode": "SHEET_DATA_ATTRIBUTES"
  },
  "SHEET_DECLARATION_ATTRIBUTES": {
    "capability": "workbook-features",
    "scope": "sheet",
    "impact": "sheet",
    "refusalCode": "SHEET_DECLARATION_ATTRIBUTES"
  },
  "COLS_ATTRIBUTES": {
    "capability": "dimensions",
    "scope": "sheet",
    "impact": "none"
  },
  "SHEET_FORMAT_EXTRAS": {
    "capability": "dimensions",
    "scope": "sheet",
    "impact": "none"
  },
  "SHEET_VIEW_GEOMETRY": {
    "capability": "dimensions",
    "scope": "sheet",
    "impact": "none"
  },
  "COLUMN_DIMENSION_EXTRAS": {
    "capability": "dimensions",
    "scope": "sheet",
    "impact": "none"
  },
  "ROW_DIMENSION_EXTRAS": {
    "capability": "dimensions",
    "scope": "sheet",
    "impact": "none"
  },
  "ROW_EXTENSIONS": {
    "capability": "extensions",
    "scope": "sheet",
    "impact": "none"
  },
  "INLINE_STRING_ATTRIBUTES": {
    "capability": "rich-text",
    "scope": "sheet",
    "impact": "cell"
  },
  "MERGED_CELLS": {
    "capability": "merges",
    "scope": "sheet",
    "impact": "none"
  },
  "CONDITIONAL_FORMATTING": {
    "capability": "conditional-formatting",
    "scope": "sheet",
    "impact": "none"
  },
  "DATA_VALIDATION": {
    "capability": "data-validation",
    "scope": "sheet",
    "impact": "none"
  },
  "HYPERLINKS": {
    "capability": "hyperlinks",
    "scope": "sheet",
    "impact": "none"
  },
  "DRAWING_REFERENCE": {
    "capability": "drawings",
    "scope": "sheet",
    "impact": "none"
  },
  "TABLE_REFERENCE": {
    "capability": "tables",
    "scope": "sheet",
    "impact": "none"
  },
  "WORKSHEET_EXTENSIONS": {
    "capability": "extensions",
    "scope": "sheet",
    "impact": "none"
  },
  "FOREIGN_WORKSHEET_MARKUP": {
    "capability": "extensions",
    "scope": "sheet",
    "impact": "none"
  },
  "UNMODELED_WORKSHEET_FEATURE": {
    "capability": "worksheet-features",
    "scope": "sheet",
    "impact": "none"
  },
  "RICH_SHARED_STRING": {
    "capability": "rich-text",
    "scope": "workbook",
    "impact": "none"
  },
  "SHARED_STRING_TABLE_ATTRIBUTES": {
    "capability": "rich-text",
    "scope": "workbook",
    "impact": "none"
  },
  "SHARED_STRING_ITEM_ATTRIBUTES": {
    "capability": "rich-text",
    "scope": "workbook",
    "impact": "none"
  },
  "SHARED_STRING_TABLE_OPAQUE_CONTENT": {
    "capability": "rich-text",
    "scope": "workbook",
    "impact": "none"
  },
  "WORKBOOK_ATTRIBUTES": {
    "capability": "workbook-features",
    "scope": "workbook",
    "impact": "none"
  },
  "SHEETS_ATTRIBUTES": {
    "capability": "workbook-features",
    "scope": "workbook",
    "impact": "none"
  },
  "UNMODELED_WORKBOOK_FEATURE": {
    "capability": "workbook-features",
    "scope": "workbook",
    "impact": "none"
  },
  "EXTERNAL_RELATIONSHIP": {
    "capability": "external-links",
    "scope": "workbook",
    "impact": "none"
  },
  "STYLE_SHEET_ATTRIBUTES": {
    "capability": "styles",
    "scope": "workbook",
    "impact": "none"
  },
  "STYLE_TABLE_ATTRIBUTES": {
    "capability": "styles",
    "scope": "workbook",
    "impact": "none"
  },
  "STYLE_TABLE_OPAQUE_CONTENT": {
    "capability": "styles",
    "scope": "workbook",
    "impact": "none"
  },
  "STYLE_RECORD_ATTRIBUTES": {
    "capability": "styles",
    "scope": "workbook",
    "impact": "none"
  },
  "STYLE_FONT_OPAQUE_CONTENT": {
    "capability": "styles",
    "scope": "workbook",
    "impact": "none"
  },
  "STYLE_XF_OPAQUE_CONTENT": {
    "capability": "styles",
    "scope": "workbook",
    "impact": "none"
  },
  "STYLE_NUMBER_FORMAT": {
    "capability": "styles",
    "scope": "style",
    "impact": "none"
  },
  "STYLE_FONT_COLOR": {
    "capability": "styles",
    "scope": "style",
    "impact": "none"
  },
  "STYLE_FILL": {
    "capability": "styles",
    "scope": "style",
    "impact": "none"
  },
  "STYLE_BORDER": {
    "capability": "styles",
    "scope": "style",
    "impact": "none"
  },
  "STYLE_HORIZONTAL_ALIGNMENT": {
    "capability": "styles",
    "scope": "style",
    "impact": "none"
  },
  "STYLE_VERTICAL_ALIGNMENT": {
    "capability": "styles",
    "scope": "style",
    "impact": "none"
  },
  "STYLE_ALIGNMENT_EXTENDED": {
    "capability": "styles",
    "scope": "style",
    "impact": "none"
  },
  "CHART_CONTENT": {
    "capability": "charts",
    "scope": "workbook",
    "impact": "none"
  },
  "PIVOT_OR_SLICER_CONTENT": {
    "capability": "pivots",
    "scope": "workbook",
    "impact": "none"
  },
  "DRAWING_OR_MEDIA_CONTENT": {
    "capability": "drawings",
    "scope": "workbook",
    "impact": "none"
  },
  "TABLE_CONTENT": {
    "capability": "tables",
    "scope": "workbook",
    "impact": "none"
  },
  "COMMENT_CONTENT": {
    "capability": "comments",
    "scope": "workbook",
    "impact": "none"
  },
  "EXTERNAL_LINK_CONTENT": {
    "capability": "external-links",
    "scope": "workbook",
    "impact": "none"
  },
  "MACRO_CONTENT": {
    "capability": "macros",
    "scope": "workbook",
    "impact": "none"
  },
  "OPAQUE_PACKAGE_PART": {
    "capability": "opaque-parts",
    "scope": "workbook",
    "impact": "none"
  }
} as const
export const XLSX_NATIVE_V2_OBJECT_BINDINGS = {
  "NativeWorkbookBorderSideV2": {
    "schemaName": "borderSide",
    "properties": [
      "color",
      "style"
    ],
    "required": [
      "color",
      "style"
    ],
    "types": {
      "color": "string",
      "style": "string"
    }
  },
  "NativeWorkbookBorderV2": {
    "schemaName": "border",
    "properties": [
      "border_id",
      "bottom",
      "left",
      "origin",
      "record_sha256",
      "right",
      "top"
    ],
    "required": [
      "origin"
    ],
    "types": {
      "border_id": "integer",
      "bottom": "NativeWorkbookBorderSideV2",
      "left": "NativeWorkbookBorderSideV2",
      "origin": "string",
      "record_sha256": "string",
      "right": "NativeWorkbookBorderSideV2",
      "top": "NativeWorkbookBorderSideV2"
    }
  },
  "NativeWorkbookCapabilityV2": {
    "schemaName": "capability",
    "properties": [
      "detail",
      "level",
      "name"
    ],
    "required": [
      "level",
      "name"
    ],
    "types": {
      "detail": "string",
      "level": "string",
      "name": "string"
    }
  },
  "NativeWorkbookCellV2": {
    "schemaName": "cell",
    "properties": [
      "column",
      "editable",
      "formula",
      "ooxml_type",
      "ref",
      "row",
      "style_id",
      "value"
    ],
    "required": [
      "column",
      "editable",
      "ref",
      "row",
      "style_id"
    ],
    "types": {
      "column": "integer",
      "editable": "boolean",
      "formula": "NativeWorkbookFormulaV2",
      "ooxml_type": "string",
      "ref": "string",
      "row": "integer",
      "style_id": "integer",
      "value": "NativeWorkbookValueV2"
    }
  },
  "NativeWorkbookColumnDimensionV2": {
    "schemaName": "columnDimension",
    "properties": [
      "best_fit",
      "column",
      "custom_width",
      "end_column",
      "hidden",
      "style_id",
      "width"
    ],
    "required": [
      "best_fit",
      "column",
      "custom_width",
      "end_column",
      "hidden"
    ],
    "types": {
      "best_fit": "boolean",
      "column": "integer",
      "custom_width": "boolean",
      "end_column": "integer",
      "hidden": "boolean",
      "style_id": "integer",
      "width": "number"
    }
  },
  "NativeWorkbookEffectiveStyleV2": {
    "schemaName": "effectiveStyle",
    "properties": [
      "bold",
      "border",
      "fill",
      "fill_color",
      "font_color",
      "font_name",
      "font_size_points",
      "horizontal_alignment",
      "italic",
      "number_format",
      "projection",
      "shrink_to_fit",
      "text_rotation",
      "unsupported",
      "vertical_alignment",
      "wrap_text"
    ],
    "required": [
      "projection",
      "unsupported"
    ],
    "types": {
      "bold": "boolean",
      "border": "NativeWorkbookBorderV2",
      "fill": "NativeWorkbookFillV2",
      "fill_color": "string",
      "font_color": "string",
      "font_name": "string",
      "font_size_points": "number",
      "horizontal_alignment": "string",
      "italic": "boolean",
      "number_format": "string",
      "projection": "string",
      "shrink_to_fit": "boolean",
      "text_rotation": "integer",
      "unsupported": "[]string",
      "vertical_alignment": "string",
      "wrap_text": "boolean"
    }
  },
  "NativeWorkbookFillV2": {
    "schemaName": "fill",
    "properties": [
      "color",
      "fill_id",
      "origin",
      "record_sha256"
    ],
    "required": [
      "origin"
    ],
    "types": {
      "color": "string",
      "fill_id": "integer",
      "origin": "string",
      "record_sha256": "string"
    }
  },
  "NativeWorkbookFormulaV2": {
    "schemaName": "formula",
    "properties": [
      "cached",
      "ref",
      "shared_index",
      "text",
      "type"
    ],
    "required": [
      "text",
      "type"
    ],
    "types": {
      "cached": "NativeWorkbookValueV2",
      "ref": "string",
      "shared_index": "integer",
      "text": "string",
      "type": "string"
    }
  },
  "NativeWorkbookMergedRangeV2": {
    "schemaName": "mergedRange",
    "properties": [
      "column",
      "editable",
      "end_column",
      "end_row",
      "ref",
      "row"
    ],
    "required": [
      "column",
      "editable",
      "end_column",
      "end_row",
      "ref",
      "row"
    ],
    "types": {
      "column": "integer",
      "editable": "boolean",
      "end_column": "integer",
      "end_row": "integer",
      "ref": "string",
      "row": "integer"
    }
  },
  "NativeWorkbookNormalStyleV2": {
    "schemaName": "normalStyle",
    "properties": [
      "font_bold",
      "font_id",
      "font_italic",
      "font_name",
      "font_record_sha256",
      "font_size_points",
      "style_xf_id"
    ],
    "required": [
      "font_bold",
      "font_id",
      "font_italic",
      "font_name",
      "font_record_sha256",
      "font_size_points",
      "style_xf_id"
    ],
    "types": {
      "font_bold": "boolean",
      "font_id": "integer",
      "font_italic": "boolean",
      "font_name": "string",
      "font_record_sha256": "string",
      "font_size_points": "number",
      "style_xf_id": "integer"
    }
  },
  "NativeWorkbookPassthroughPartV2": {
    "schemaName": "passthroughPart",
    "properties": [
      "byte_length",
      "content_type",
      "part_name",
      "policy",
      "sha256"
    ],
    "required": [
      "byte_length",
      "content_type",
      "part_name",
      "policy",
      "sha256"
    ],
    "types": {
      "byte_length": "integer",
      "content_type": "string",
      "part_name": "string",
      "policy": "string",
      "sha256": "string"
    }
  },
  "NativeWorkbookRichRunV2": {
    "schemaName": "richRun",
    "properties": [
      "bold",
      "font_color",
      "font_name",
      "font_size_points",
      "italic",
      "text"
    ],
    "required": [
      "text"
    ],
    "types": {
      "bold": "boolean",
      "font_color": "string",
      "font_name": "string",
      "font_size_points": "number",
      "italic": "boolean",
      "text": "string"
    }
  },
  "NativeWorkbookRowDimensionV2": {
    "schemaName": "rowDimension",
    "properties": [
      "custom_height",
      "height_points",
      "hidden",
      "row",
      "style_id"
    ],
    "required": [
      "custom_height",
      "hidden",
      "row"
    ],
    "types": {
      "custom_height": "boolean",
      "height_points": "number",
      "hidden": "boolean",
      "row": "integer",
      "style_id": "integer"
    }
  },
  "NativeWorkbookSheetFormatV2": {
    "schemaName": "sheetFormat",
    "properties": [
      "base_column_width",
      "custom_height",
      "default_column_width",
      "default_row_height_points",
      "zero_height"
    ],
    "required": [
      "custom_height",
      "default_row_height_points",
      "zero_height"
    ],
    "types": {
      "base_column_width": "integer",
      "custom_height": "boolean",
      "default_column_width": "number",
      "default_row_height_points": "number",
      "zero_height": "boolean"
    }
  },
  "NativeWorkbookSheetV2": {
    "schemaName": "sheet",
    "properties": [
      "cells",
      "columns",
      "editable",
      "id",
      "merged_ranges",
      "name",
      "order",
      "part_name",
      "refusal_code",
      "rows",
      "sheet_format",
      "state"
    ],
    "required": [
      "cells",
      "columns",
      "editable",
      "id",
      "merged_ranges",
      "name",
      "order",
      "part_name",
      "rows",
      "state"
    ],
    "types": {
      "cells": "[]NativeWorkbookCellV2",
      "columns": "[]NativeWorkbookColumnDimensionV2",
      "editable": "boolean",
      "id": "string",
      "merged_ranges": "[]NativeWorkbookMergedRangeV2",
      "name": "string",
      "order": "integer",
      "part_name": "string",
      "refusal_code": "string",
      "rows": "[]NativeWorkbookRowDimensionV2",
      "sheet_format": "NativeWorkbookSheetFormatV2",
      "state": "string"
    }
  },
  "NativeWorkbookSourceV2": {
    "schemaName": "source",
    "properties": [
      "authority",
      "dialect",
      "package_sha256",
      "workbook_part"
    ],
    "required": [
      "authority",
      "dialect",
      "package_sha256",
      "workbook_part"
    ],
    "types": {
      "authority": "string",
      "dialect": "string",
      "package_sha256": "string",
      "workbook_part": "string"
    }
  },
  "NativeWorkbookStyleV2": {
    "schemaName": "style",
    "properties": [
      "effective",
      "id",
      "raw_projection_sha256"
    ],
    "required": [
      "effective",
      "id",
      "raw_projection_sha256"
    ],
    "types": {
      "effective": "NativeWorkbookEffectiveStyleV2",
      "id": "integer",
      "raw_projection_sha256": "string"
    }
  },
  "NativeWorkbookUnsupportedV2": {
    "schemaName": "unsupported",
    "properties": [
      "capability",
      "cell_ref",
      "code",
      "id",
      "message",
      "part_name",
      "preservation",
      "range_ref",
      "scope_id"
    ],
    "required": [
      "capability",
      "code",
      "id",
      "message",
      "preservation",
      "scope_id"
    ],
    "types": {
      "capability": "string",
      "cell_ref": "string",
      "code": "string",
      "id": "string",
      "message": "string",
      "part_name": "string",
      "preservation": "string",
      "range_ref": "string",
      "scope_id": "string"
    }
  },
  "NativeWorkbookV2": {
    "schemaName": "$root",
    "properties": [
      "capabilities",
      "date1904",
      "document_id",
      "normal_style",
      "passthrough_parts",
      "protocol",
      "revision",
      "schema_sha256",
      "sheets",
      "source",
      "styles",
      "unsupported",
      "version"
    ],
    "required": [
      "capabilities",
      "document_id",
      "passthrough_parts",
      "protocol",
      "revision",
      "schema_sha256",
      "sheets",
      "source",
      "styles",
      "unsupported",
      "version"
    ],
    "types": {
      "capabilities": "[]NativeWorkbookCapabilityV2",
      "date1904": "boolean",
      "document_id": "string",
      "normal_style": "NativeWorkbookNormalStyleV2",
      "passthrough_parts": "[]NativeWorkbookPassthroughPartV2",
      "protocol": "string",
      "revision": "string",
      "schema_sha256": "string",
      "sheets": "[]NativeWorkbookSheetV2",
      "source": "NativeWorkbookSourceV2",
      "styles": "[]NativeWorkbookStyleV2",
      "unsupported": "[]NativeWorkbookUnsupportedV2",
      "version": "integer"
    }
  },
  "NativeWorkbookValueV2": {
    "schemaName": "value",
    "properties": [
      "kind",
      "lexical",
      "rich",
      "runs",
      "storage",
      "text"
    ],
    "required": [
      "kind",
      "rich",
      "storage"
    ],
    "types": {
      "kind": "string",
      "lexical": "string",
      "rich": "boolean",
      "runs": "[]NativeWorkbookRichRunV2",
      "storage": "string",
      "text": "string"
    }
  }
} as const
export const XLSX_NATIVE_V2_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.injoffice.dev/xlsx/native-v2.schema.json",
  "title": "InjOffice native XLSX workbook v2",
  "description": "Renderer-neutral, source-authoritative projection emitted by go/xlsxpatch.",
  "type": "object",
  "x-binding-name": "NativeWorkbookV2",
  "x-media-type": "application/vnd.injoffice.xlsx-native.v2+json",
  "x-resource-limits": {
    "maxJsonBytes": 134217728,
    "maxJsonDepth": 256,
    "maxJsonTokens": 4000000,
    "maxSheets": 1024,
    "maxRows": 1048576,
    "maxColumns": 16384,
    "maxCells": 1000000,
    "maxMergedRanges": 100000,
    "maxStyles": 100000,
    "maxInventory": 10000,
    "maxTextBytes": 33554432,
    "maxPartBytes": 67108864,
    "maxIssues": 100
  },
  "x-unsupported-classifications": {
    "CELL_ATTRIBUTES": {
      "capability": "cell-markup",
      "scope": "sheet",
      "impact": "cell"
    },
    "CELL_EXTENSIONS": {
      "capability": "extensions",
      "scope": "sheet",
      "impact": "cell"
    },
    "CELL_METADATA": {
      "capability": "cell-metadata",
      "scope": "sheet",
      "impact": "cell"
    },
    "OPAQUE_CELL_MARKUP": {
      "capability": "cell-markup",
      "scope": "sheet",
      "impact": "cell"
    },
    "RICH_CELL_STRING": {
      "capability": "rich-text",
      "scope": "sheet",
      "impact": "cell"
    },
    "FORMULA_ATTRIBUTES": {
      "capability": "formula-groups",
      "scope": "sheet",
      "impact": "cell"
    },
    "FORMULA_SHARED": {
      "capability": "formula-groups",
      "scope": "sheet",
      "impact": "cell"
    },
    "FORMULA_ARRAY": {
      "capability": "formula-groups",
      "scope": "sheet",
      "impact": "cell"
    },
    "FORMULA_DATATABLE": {
      "capability": "formula-groups",
      "scope": "sheet",
      "impact": "cell"
    },
    "FORMULA_GROUP_RANGE": {
      "capability": "formula-groups",
      "scope": "sheet",
      "impact": "range"
    },
    "SHEET_PROTECTION": {
      "capability": "protection",
      "scope": "sheet",
      "impact": "sheet",
      "refusalCode": "SHEET_PROTECTION"
    },
    "WORKSHEET_ATTRIBUTES": {
      "capability": "worksheet-features",
      "scope": "sheet",
      "impact": "sheet",
      "refusalCode": "UNSAFE_WORKSHEET_ATTRIBUTES"
    },
    "SHEET_DATA_ATTRIBUTES": {
      "capability": "worksheet-features",
      "scope": "sheet",
      "impact": "sheet",
      "refusalCode": "SHEET_DATA_ATTRIBUTES"
    },
    "SHEET_DECLARATION_ATTRIBUTES": {
      "capability": "workbook-features",
      "scope": "sheet",
      "impact": "sheet",
      "refusalCode": "SHEET_DECLARATION_ATTRIBUTES"
    },
    "COLS_ATTRIBUTES": {
      "capability": "dimensions",
      "scope": "sheet",
      "impact": "none"
    },
    "SHEET_FORMAT_EXTRAS": {
      "capability": "dimensions",
      "scope": "sheet",
      "impact": "none"
    },
    "SHEET_VIEW_GEOMETRY": {
      "capability": "dimensions",
      "scope": "sheet",
      "impact": "none"
    },
    "COLUMN_DIMENSION_EXTRAS": {
      "capability": "dimensions",
      "scope": "sheet",
      "impact": "none"
    },
    "ROW_DIMENSION_EXTRAS": {
      "capability": "dimensions",
      "scope": "sheet",
      "impact": "none"
    },
    "ROW_EXTENSIONS": {
      "capability": "extensions",
      "scope": "sheet",
      "impact": "none"
    },
    "INLINE_STRING_ATTRIBUTES": {
      "capability": "rich-text",
      "scope": "sheet",
      "impact": "cell"
    },
    "MERGED_CELLS": {
      "capability": "merges",
      "scope": "sheet",
      "impact": "none"
    },
    "CONDITIONAL_FORMATTING": {
      "capability": "conditional-formatting",
      "scope": "sheet",
      "impact": "none"
    },
    "DATA_VALIDATION": {
      "capability": "data-validation",
      "scope": "sheet",
      "impact": "none"
    },
    "HYPERLINKS": {
      "capability": "hyperlinks",
      "scope": "sheet",
      "impact": "none"
    },
    "DRAWING_REFERENCE": {
      "capability": "drawings",
      "scope": "sheet",
      "impact": "none"
    },
    "TABLE_REFERENCE": {
      "capability": "tables",
      "scope": "sheet",
      "impact": "none"
    },
    "WORKSHEET_EXTENSIONS": {
      "capability": "extensions",
      "scope": "sheet",
      "impact": "none"
    },
    "FOREIGN_WORKSHEET_MARKUP": {
      "capability": "extensions",
      "scope": "sheet",
      "impact": "none"
    },
    "UNMODELED_WORKSHEET_FEATURE": {
      "capability": "worksheet-features",
      "scope": "sheet",
      "impact": "none"
    },
    "RICH_SHARED_STRING": {
      "capability": "rich-text",
      "scope": "workbook",
      "impact": "none"
    },
    "SHARED_STRING_TABLE_ATTRIBUTES": {
      "capability": "rich-text",
      "scope": "workbook",
      "impact": "none"
    },
    "SHARED_STRING_ITEM_ATTRIBUTES": {
      "capability": "rich-text",
      "scope": "workbook",
      "impact": "none"
    },
    "SHARED_STRING_TABLE_OPAQUE_CONTENT": {
      "capability": "rich-text",
      "scope": "workbook",
      "impact": "none"
    },
    "WORKBOOK_ATTRIBUTES": {
      "capability": "workbook-features",
      "scope": "workbook",
      "impact": "none"
    },
    "SHEETS_ATTRIBUTES": {
      "capability": "workbook-features",
      "scope": "workbook",
      "impact": "none"
    },
    "UNMODELED_WORKBOOK_FEATURE": {
      "capability": "workbook-features",
      "scope": "workbook",
      "impact": "none"
    },
    "EXTERNAL_RELATIONSHIP": {
      "capability": "external-links",
      "scope": "workbook",
      "impact": "none"
    },
    "STYLE_SHEET_ATTRIBUTES": {
      "capability": "styles",
      "scope": "workbook",
      "impact": "none"
    },
    "STYLE_TABLE_ATTRIBUTES": {
      "capability": "styles",
      "scope": "workbook",
      "impact": "none"
    },
    "STYLE_TABLE_OPAQUE_CONTENT": {
      "capability": "styles",
      "scope": "workbook",
      "impact": "none"
    },
    "STYLE_RECORD_ATTRIBUTES": {
      "capability": "styles",
      "scope": "workbook",
      "impact": "none"
    },
    "STYLE_FONT_OPAQUE_CONTENT": {
      "capability": "styles",
      "scope": "workbook",
      "impact": "none"
    },
    "STYLE_XF_OPAQUE_CONTENT": {
      "capability": "styles",
      "scope": "workbook",
      "impact": "none"
    },
    "STYLE_NUMBER_FORMAT": {
      "capability": "styles",
      "scope": "style",
      "impact": "none"
    },
    "STYLE_FONT_COLOR": {
      "capability": "styles",
      "scope": "style",
      "impact": "none"
    },
    "STYLE_FILL": {
      "capability": "styles",
      "scope": "style",
      "impact": "none"
    },
    "STYLE_BORDER": {
      "capability": "styles",
      "scope": "style",
      "impact": "none"
    },
    "STYLE_HORIZONTAL_ALIGNMENT": {
      "capability": "styles",
      "scope": "style",
      "impact": "none"
    },
    "STYLE_VERTICAL_ALIGNMENT": {
      "capability": "styles",
      "scope": "style",
      "impact": "none"
    },
    "STYLE_ALIGNMENT_EXTENDED": {
      "capability": "styles",
      "scope": "style",
      "impact": "none"
    },
    "CHART_CONTENT": {
      "capability": "charts",
      "scope": "workbook",
      "impact": "none"
    },
    "PIVOT_OR_SLICER_CONTENT": {
      "capability": "pivots",
      "scope": "workbook",
      "impact": "none"
    },
    "DRAWING_OR_MEDIA_CONTENT": {
      "capability": "drawings",
      "scope": "workbook",
      "impact": "none"
    },
    "TABLE_CONTENT": {
      "capability": "tables",
      "scope": "workbook",
      "impact": "none"
    },
    "COMMENT_CONTENT": {
      "capability": "comments",
      "scope": "workbook",
      "impact": "none"
    },
    "EXTERNAL_LINK_CONTENT": {
      "capability": "external-links",
      "scope": "workbook",
      "impact": "none"
    },
    "MACRO_CONTENT": {
      "capability": "macros",
      "scope": "workbook",
      "impact": "none"
    },
    "OPAQUE_PACKAGE_PART": {
      "capability": "opaque-parts",
      "scope": "workbook",
      "impact": "none"
    }
  },
  "additionalProperties": false,
  "required": [
    "protocol",
    "version",
    "schema_sha256",
    "document_id",
    "revision",
    "source",
    "sheets",
    "styles",
    "capabilities",
    "passthrough_parts",
    "unsupported"
  ],
  "properties": {
    "protocol": {
      "const": "injoffice.xlsx.native"
    },
    "version": {
      "const": 2
    },
    "schema_sha256": {
      "type": "string",
      "pattern": "^sha256:[0-9a-f]{64}$"
    },
    "document_id": {
      "type": "string",
      "minLength": 1,
      "maxLength": 256,
      "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,255}$"
    },
    "revision": {
      "type": "string",
      "pattern": "^rev:[0-9a-f]{64}$"
    },
    "source": {
      "$ref": "#/$defs/source"
    },
    "normal_style": {
      "$ref": "#/$defs/normalStyle"
    },
    "date1904": {
      "type": "boolean"
    },
    "sheets": {
      "type": "array",
      "minItems": 1,
      "maxItems": 1024,
      "items": {
        "$ref": "#/$defs/sheet"
      }
    },
    "styles": {
      "type": "array",
      "minItems": 1,
      "maxItems": 100000,
      "items": {
        "$ref": "#/$defs/style"
      }
    },
    "capabilities": {
      "type": "array",
      "minItems": 5,
      "maxItems": 5,
      "items": {
        "$ref": "#/$defs/capability"
      }
    },
    "passthrough_parts": {
      "type": "array",
      "maxItems": 10000,
      "items": {
        "$ref": "#/$defs/passthroughPart"
      }
    },
    "unsupported": {
      "type": "array",
      "maxItems": 10000,
      "items": {
        "$ref": "#/$defs/unsupported"
      }
    }
  },
  "$defs": {
    "dialect": {
      "type": "string",
      "enum": [
        "transitional",
        "strict"
      ],
      "x-binding-name": "NativeWorkbookDialect"
    },
    "sheetState": {
      "type": "string",
      "enum": [
        "visible",
        "hidden",
        "veryHidden"
      ],
      "x-binding-name": "NativeSheetState"
    },
    "valueKind": {
      "type": "string",
      "enum": [
        "number",
        "boolean",
        "error",
        "date",
        "string"
      ],
      "x-binding-name": "NativeValueKind"
    },
    "valueStorage": {
      "type": "string",
      "enum": [
        "number",
        "boolean",
        "error",
        "date",
        "formula-string",
        "shared",
        "inline"
      ],
      "x-binding-name": "NativeValueStorage"
    },
    "ooxmlCellType": {
      "type": "string",
      "enum": [
        "n",
        "s",
        "str",
        "inlineStr",
        "b",
        "e",
        "d"
      ],
      "x-binding-name": "NativeOOXMLCellType"
    },
    "formulaType": {
      "type": "string",
      "enum": [
        "normal",
        "shared",
        "array",
        "dataTable"
      ],
      "x-binding-name": "NativeFormulaType"
    },
    "styleProjection": {
      "type": "string",
      "enum": [
        "full",
        "partial"
      ],
      "x-binding-name": "NativeStyleProjection"
    },
    "styleUnsupported": {
      "type": "string",
      "enum": [
        "alignment-extended",
        "border",
        "fill",
        "font-color",
        "horizontal-alignment",
        "number-format",
        "vertical-alignment"
      ],
      "x-binding-name": "NativeStyleUnsupportedCode"
    },
    "borderStyle": {
      "type": "string",
      "enum": [
        "dashDot",
        "dashDotDot",
        "dashed",
        "dotted",
        "double",
        "hair",
        "medium",
        "mediumDashDot",
        "mediumDashDotDot",
        "mediumDashed",
        "slantDashDot",
        "thick",
        "thin"
      ],
      "x-binding-name": "NativeBorderStyle"
    },
    "borderOrigin": {
      "type": "string",
      "enum": [
        "implicit-default",
        "styles-record"
      ],
      "x-binding-name": "NativeBorderOrigin"
    },
    "horizontalAlignment": {
      "type": "string",
      "enum": [
        "general",
        "left",
        "center",
        "right"
      ],
      "x-binding-name": "NativeHorizontalAlignment"
    },
    "verticalAlignment": {
      "type": "string",
      "enum": [
        "top",
        "middle",
        "bottom"
      ],
      "x-binding-name": "NativeVerticalAlignment"
    },
    "source": {
      "type": "object",
      "x-binding-name": "NativeWorkbookSourceV2",
      "additionalProperties": false,
      "required": [
        "package_sha256",
        "workbook_part",
        "dialect",
        "authority"
      ],
      "properties": {
        "package_sha256": {
          "type": "string",
          "pattern": "^sha256:[0-9a-f]{64}$"
        },
        "workbook_part": {
          "type": "string",
          "minLength": 1,
          "maxLength": 8192
        },
        "dialect": {
          "$ref": "#/$defs/dialect"
        },
        "authority": {
          "const": "exact-package-bytes"
        }
      }
    },
    "capability": {
      "type": "object",
      "x-binding-name": "NativeWorkbookCapabilityV2",
      "additionalProperties": false,
      "required": [
        "name",
        "level"
      ],
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1,
          "maxLength": 128,
          "pattern": "^[a-z][a-z0-9-]{0,127}$"
        },
        "level": {
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },
        "detail": {
          "type": "string",
          "minLength": 1,
          "maxLength": 8192
        }
      }
    },
    "passthroughPart": {
      "type": "object",
      "x-binding-name": "NativeWorkbookPassthroughPartV2",
      "additionalProperties": false,
      "required": [
        "part_name",
        "content_type",
        "byte_length",
        "sha256",
        "policy"
      ],
      "properties": {
        "part_name": {
          "type": "string",
          "minLength": 1,
          "maxLength": 8192
        },
        "content_type": {
          "type": "string",
          "minLength": 1,
          "maxLength": 1024
        },
        "byte_length": {
          "type": "integer",
          "minimum": 0,
          "maximum": 67108864
        },
        "sha256": {
          "type": "string",
          "pattern": "^sha256:[0-9a-f]{64}$"
        },
        "policy": {
          "const": "preserve-exact"
        }
      }
    },
    "unsupported": {
      "type": "object",
      "x-binding-name": "NativeWorkbookUnsupportedV2",
      "additionalProperties": false,
      "required": [
        "id",
        "code",
        "capability",
        "scope_id",
        "preservation",
        "message"
      ],
      "properties": {
        "id": {
          "type": "string",
          "pattern": "^unsupported:[0-9a-f]{64}$"
        },
        "code": {
          "type": "string",
          "pattern": "^[A-Z][A-Z0-9_]{0,127}$"
        },
        "capability": {
          "type": "string",
          "pattern": "^[a-z][a-z0-9-]{0,127}$"
        },
        "scope_id": {
          "type": "string",
          "minLength": 1,
          "maxLength": 8192
        },
        "part_name": {
          "type": "string",
          "minLength": 1,
          "maxLength": 8192
        },
        "cell_ref": {
          "type": "string",
          "minLength": 1,
          "maxLength": 16
        },
        "range_ref": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64
        },
        "preservation": {
          "const": "preserve-exact"
        },
        "message": {
          "type": "string",
          "minLength": 1,
          "maxLength": 8192
        }
      }
    },
    "value": {
      "type": "object",
      "x-binding-name": "NativeWorkbookValueV2",
      "additionalProperties": false,
      "required": [
        "kind",
        "storage",
        "rich"
      ],
      "properties": {
        "kind": {
          "$ref": "#/$defs/valueKind"
        },
        "storage": {
          "$ref": "#/$defs/valueStorage"
        },
        "lexical": {
          "type": "string",
          "minLength": 1,
          "maxLength": 32767
        },
        "text": {
          "type": "string",
          "maxLength": 32767,
          "x-maxUtf16Length": 32767
        },
        "rich": {
          "type": "boolean"
        },
        "runs": {
          "type": "array",
          "minItems": 1,
          "maxItems": 4096,
          "items": {
            "$ref": "#/$defs/richRun"
          }
        }
      }
    },
    "richRun": {
      "type": "object",
      "x-binding-name": "NativeWorkbookRichRunV2",
      "additionalProperties": false,
      "required": [
        "text"
      ],
      "properties": {
        "text": {
          "type": "string",
          "minLength": 1,
          "maxLength": 32767,
          "x-maxUtf16Length": 32767
        },
        "font_name": {
          "type": "string",
          "minLength": 1,
          "maxLength": 255,
          "x-maxUtf16Length": 255
        },
        "bold": {
          "type": "boolean"
        },
        "italic": {
          "type": "boolean"
        },
        "font_size_points": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 409
        },
        "font_color": {
          "type": "string",
          "pattern": "^#[0-9A-F]{6}$"
        }
      }
    },
    "formula": {
      "type": "object",
      "x-binding-name": "NativeWorkbookFormulaV2",
      "additionalProperties": false,
      "required": [
        "text",
        "type"
      ],
      "properties": {
        "text": {
          "type": "string",
          "maxLength": 8191,
          "x-maxUtf16Length": 8191
        },
        "type": {
          "$ref": "#/$defs/formulaType"
        },
        "ref": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64
        },
        "shared_index": {
          "type": "integer",
          "minimum": 0,
          "maximum": 4294967295
        },
        "cached": {
          "$ref": "#/$defs/value"
        }
      }
    },
    "cell": {
      "type": "object",
      "x-binding-name": "NativeWorkbookCellV2",
      "additionalProperties": false,
      "required": [
        "row",
        "column",
        "ref",
        "style_id",
        "editable"
      ],
      "properties": {
        "row": {
          "type": "integer",
          "minimum": 0,
          "maximum": 1048575
        },
        "column": {
          "type": "integer",
          "minimum": 0,
          "maximum": 16383
        },
        "ref": {
          "type": "string",
          "minLength": 1,
          "maxLength": 16
        },
        "ooxml_type": {
          "$ref": "#/$defs/ooxmlCellType"
        },
        "style_id": {
          "type": "integer",
          "minimum": 0,
          "maximum": 4294967295
        },
        "value": {
          "$ref": "#/$defs/value"
        },
        "formula": {
          "$ref": "#/$defs/formula"
        },
        "editable": {
          "type": "boolean"
        }
      }
    },
    "mergedRange": {
      "type": "object",
      "x-binding-name": "NativeWorkbookMergedRangeV2",
      "additionalProperties": false,
      "required": [
        "ref",
        "row",
        "column",
        "end_row",
        "end_column",
        "editable"
      ],
      "properties": {
        "ref": {
          "type": "string",
          "minLength": 3,
          "maxLength": 33
        },
        "row": {
          "type": "integer",
          "minimum": 0,
          "maximum": 1048575
        },
        "column": {
          "type": "integer",
          "minimum": 0,
          "maximum": 16383
        },
        "end_row": {
          "type": "integer",
          "minimum": 0,
          "maximum": 1048575
        },
        "end_column": {
          "type": "integer",
          "minimum": 0,
          "maximum": 16383
        },
        "editable": {
          "const": false
        }
      }
    },
    "sheetFormat": {
      "type": "object",
      "x-binding-name": "NativeWorkbookSheetFormatV2",
      "additionalProperties": false,
      "required": [
        "default_row_height_points",
        "custom_height",
        "zero_height"
      ],
      "properties": {
        "base_column_width": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        },
        "default_column_width": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 255
        },
        "default_row_height_points": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 409.5
        },
        "custom_height": {
          "type": "boolean"
        },
        "zero_height": {
          "type": "boolean"
        }
      }
    },
    "normalStyle": {
      "type": "object",
      "x-binding-name": "NativeWorkbookNormalStyleV2",
      "additionalProperties": false,
      "required": [
        "style_xf_id",
        "font_id",
        "font_name",
        "font_size_points",
        "font_bold",
        "font_italic",
        "font_record_sha256"
      ],
      "properties": {
        "style_xf_id": {
          "type": "integer",
          "minimum": 0,
          "maximum": 4294967295
        },
        "font_id": {
          "type": "integer",
          "minimum": 0,
          "maximum": 4294967295
        },
        "font_name": {
          "type": "string",
          "minLength": 1,
          "maxLength": 255,
          "x-maxUtf16Length": 255
        },
        "font_size_points": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 409.5
        },
        "font_bold": {
          "type": "boolean"
        },
        "font_italic": {
          "type": "boolean"
        },
        "font_record_sha256": {
          "type": "string",
          "pattern": "^sha256:[0-9a-f]{64}$"
        }
      }
    },
    "rowDimension": {
      "type": "object",
      "x-binding-name": "NativeWorkbookRowDimensionV2",
      "additionalProperties": false,
      "required": [
        "row",
        "hidden",
        "custom_height"
      ],
      "properties": {
        "row": {
          "type": "integer",
          "minimum": 0,
          "maximum": 1048575
        },
        "height_points": {
          "type": "number",
          "minimum": 0,
          "maximum": 409.5
        },
        "hidden": {
          "type": "boolean"
        },
        "custom_height": {
          "type": "boolean"
        },
        "style_id": {
          "type": "integer",
          "minimum": 0,
          "maximum": 4294967295
        }
      }
    },
    "columnDimension": {
      "type": "object",
      "x-binding-name": "NativeWorkbookColumnDimensionV2",
      "additionalProperties": false,
      "required": [
        "column",
        "end_column",
        "hidden",
        "custom_width",
        "best_fit"
      ],
      "properties": {
        "column": {
          "type": "integer",
          "minimum": 0,
          "maximum": 16383
        },
        "end_column": {
          "type": "integer",
          "minimum": 0,
          "maximum": 16383
        },
        "width": {
          "type": "number",
          "minimum": 0,
          "maximum": 255
        },
        "hidden": {
          "type": "boolean"
        },
        "custom_width": {
          "type": "boolean"
        },
        "best_fit": {
          "type": "boolean"
        },
        "style_id": {
          "type": "integer",
          "minimum": 0,
          "maximum": 4294967295
        }
      }
    },
    "borderSide": {
      "type": "object",
      "x-binding-name": "NativeWorkbookBorderSideV2",
      "additionalProperties": false,
      "required": [
        "style",
        "color"
      ],
      "properties": {
        "style": {
          "$ref": "#/$defs/borderStyle"
        },
        "color": {
          "type": "string",
          "pattern": "^#[0-9A-F]{6}$"
        }
      }
    },
    "border": {
      "type": "object",
      "x-binding-name": "NativeWorkbookBorderV2",
      "additionalProperties": false,
      "required": [
        "origin"
      ],
      "properties": {
        "origin": {
          "$ref": "#/$defs/borderOrigin"
        },
        "border_id": {
          "type": "integer",
          "minimum": 0,
          "maximum": 4294967295
        },
        "record_sha256": {
          "type": "string",
          "pattern": "^sha256:[0-9a-f]{64}$"
        },
        "left": {
          "$ref": "#/$defs/borderSide"
        },
        "right": {
          "$ref": "#/$defs/borderSide"
        },
        "top": {
          "$ref": "#/$defs/borderSide"
        },
        "bottom": {
          "$ref": "#/$defs/borderSide"
        }
      }
    },
    "fill": {
      "type": "object",
      "x-binding-name": "NativeWorkbookFillV2",
      "additionalProperties": false,
      "required": [
        "origin"
      ],
      "properties": {
        "origin": {
          "$ref": "#/$defs/borderOrigin"
        },
        "fill_id": {
          "type": "integer",
          "minimum": 0,
          "maximum": 4294967295
        },
        "record_sha256": {
          "type": "string",
          "pattern": "^sha256:[0-9a-f]{64}$"
        },
        "color": {
          "type": "string",
          "pattern": "^#[0-9A-F]{6}$"
        }
      }
    },
    "effectiveStyle": {
      "type": "object",
      "x-binding-name": "NativeWorkbookEffectiveStyleV2",
      "additionalProperties": false,
      "required": [
        "projection",
        "unsupported"
      ],
      "properties": {
        "number_format": {
          "type": "string",
          "minLength": 1,
          "maxLength": 255,
          "x-maxUtf16Length": 255
        },
        "font_name": {
          "type": "string",
          "minLength": 1,
          "maxLength": 255,
          "x-maxUtf16Length": 255
        },
        "font_size_points": {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 409
        },
        "bold": {
          "type": "boolean"
        },
        "italic": {
          "type": "boolean"
        },
        "font_color": {
          "type": "string",
          "pattern": "^#[0-9A-F]{6}$"
        },
        "fill_color": {
          "type": "string",
          "pattern": "^#[0-9A-F]{6}$"
        },
        "fill": {
          "$ref": "#/$defs/fill"
        },
        "border": {
          "$ref": "#/$defs/border"
        },
        "horizontal_alignment": {
          "$ref": "#/$defs/horizontalAlignment"
        },
        "vertical_alignment": {
          "$ref": "#/$defs/verticalAlignment"
        },
        "wrap_text": {
          "type": "boolean"
        },
        "shrink_to_fit": {
          "type": "boolean"
        },
        "text_rotation": {
          "type": "integer",
          "enum": [
            0,
            90,
            180,
            270
          ]
        },
        "projection": {
          "$ref": "#/$defs/styleProjection"
        },
        "unsupported": {
          "type": "array",
          "maxItems": 7,
          "items": {
            "$ref": "#/$defs/styleUnsupported"
          }
        }
      }
    },
    "style": {
      "type": "object",
      "x-binding-name": "NativeWorkbookStyleV2",
      "additionalProperties": false,
      "required": [
        "id",
        "effective",
        "raw_projection_sha256"
      ],
      "properties": {
        "id": {
          "type": "integer",
          "minimum": 0,
          "maximum": 4294967295
        },
        "effective": {
          "$ref": "#/$defs/effectiveStyle"
        },
        "raw_projection_sha256": {
          "type": "string",
          "pattern": "^sha256:[0-9a-f]{64}$"
        }
      }
    },
    "sheet": {
      "type": "object",
      "x-binding-name": "NativeWorkbookSheetV2",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "order",
        "state",
        "part_name",
        "rows",
        "columns",
        "cells",
        "merged_ranges",
        "editable"
      ],
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1,
          "maxLength": 10,
          "pattern": "^[1-9][0-9]{0,9}$"
        },
        "name": {
          "type": "string",
          "minLength": 1,
          "maxLength": 31,
          "x-maxUtf16Length": 31
        },
        "order": {
          "type": "integer",
          "minimum": 0,
          "maximum": 1023
        },
        "state": {
          "$ref": "#/$defs/sheetState"
        },
        "part_name": {
          "type": "string",
          "minLength": 1,
          "maxLength": 8192
        },
        "sheet_format": {
          "$ref": "#/$defs/sheetFormat"
        },
        "rows": {
          "type": "array",
          "maxItems": 1048576,
          "items": {
            "$ref": "#/$defs/rowDimension"
          }
        },
        "columns": {
          "type": "array",
          "maxItems": 16384,
          "items": {
            "$ref": "#/$defs/columnDimension"
          }
        },
        "cells": {
          "type": "array",
          "maxItems": 1000000,
          "items": {
            "$ref": "#/$defs/cell"
          }
        },
        "merged_ranges": {
          "type": "array",
          "maxItems": 100000,
          "items": {
            "$ref": "#/$defs/mergedRange"
          }
        },
        "editable": {
          "type": "boolean"
        },
        "refusal_code": {
          "type": "string",
          "minLength": 1,
          "maxLength": 128,
          "pattern": "^[A-Z][A-Z0-9_]{0,127}$"
        }
      }
    }
  }
} as const

export interface NativeWorkbookV2 {
  readonly protocol: "injoffice.xlsx.native"
  readonly version: 2
  readonly schema_sha256: string
  readonly document_id: string
  readonly revision: string
  readonly source: NativeWorkbookSourceV2
  readonly normal_style?: NativeWorkbookNormalStyleV2
  readonly date1904?: boolean
  readonly sheets: ReadonlyArray<NativeWorkbookSheetV2>
  readonly styles: ReadonlyArray<NativeWorkbookStyleV2>
  readonly capabilities: ReadonlyArray<NativeWorkbookCapabilityV2>
  readonly passthrough_parts: ReadonlyArray<NativeWorkbookPassthroughPartV2>
  readonly unsupported: ReadonlyArray<NativeWorkbookUnsupportedV2>
}

export type NativeWorkbookDialect = "transitional" | "strict"

export type NativeSheetState = "visible" | "hidden" | "veryHidden"

export type NativeValueKind = "number" | "boolean" | "error" | "date" | "string"

export type NativeValueStorage = "number" | "boolean" | "error" | "date" | "formula-string" | "shared" | "inline"

export type NativeOOXMLCellType = "n" | "s" | "str" | "inlineStr" | "b" | "e" | "d"

export type NativeFormulaType = "normal" | "shared" | "array" | "dataTable"

export type NativeStyleProjection = "full" | "partial"

export type NativeStyleUnsupportedCode = "alignment-extended" | "border" | "fill" | "font-color" | "horizontal-alignment" | "number-format" | "vertical-alignment"

export type NativeBorderStyle = "dashDot" | "dashDotDot" | "dashed" | "dotted" | "double" | "hair" | "medium" | "mediumDashDot" | "mediumDashDotDot" | "mediumDashed" | "slantDashDot" | "thick" | "thin"

export type NativeBorderOrigin = "implicit-default" | "styles-record"

export type NativeHorizontalAlignment = "general" | "left" | "center" | "right"

export type NativeVerticalAlignment = "top" | "middle" | "bottom"

export interface NativeWorkbookSourceV2 {
  readonly package_sha256: string
  readonly workbook_part: string
  readonly dialect: NativeWorkbookDialect
  readonly authority: "exact-package-bytes"
}

export interface NativeWorkbookCapabilityV2 {
  readonly name: string
  readonly level: string
  readonly detail?: string
}

export interface NativeWorkbookPassthroughPartV2 {
  readonly part_name: string
  readonly content_type: string
  readonly byte_length: number
  readonly sha256: string
  readonly policy: "preserve-exact"
}

export interface NativeWorkbookUnsupportedV2 {
  readonly id: string
  readonly code: string
  readonly capability: string
  readonly scope_id: string
  readonly part_name?: string
  readonly cell_ref?: string
  readonly range_ref?: string
  readonly preservation: "preserve-exact"
  readonly message: string
}

export interface NativeWorkbookValueV2 {
  readonly kind: NativeValueKind
  readonly storage: NativeValueStorage
  readonly lexical?: string
  readonly text?: string
  readonly rich: boolean
  readonly runs?: ReadonlyArray<NativeWorkbookRichRunV2>
}

export interface NativeWorkbookRichRunV2 {
  readonly text: string
  readonly font_name?: string
  readonly bold?: boolean
  readonly italic?: boolean
  readonly font_size_points?: number
  readonly font_color?: string
}

export interface NativeWorkbookFormulaV2 {
  readonly text: string
  readonly type: NativeFormulaType
  readonly ref?: string
  readonly shared_index?: number
  readonly cached?: NativeWorkbookValueV2
}

export interface NativeWorkbookCellV2 {
  readonly row: number
  readonly column: number
  readonly ref: string
  readonly ooxml_type?: NativeOOXMLCellType
  readonly style_id: number
  readonly value?: NativeWorkbookValueV2
  readonly formula?: NativeWorkbookFormulaV2
  readonly editable: boolean
}

export interface NativeWorkbookMergedRangeV2 {
  readonly ref: string
  readonly row: number
  readonly column: number
  readonly end_row: number
  readonly end_column: number
  readonly editable: false
}

export interface NativeWorkbookSheetFormatV2 {
  readonly base_column_width?: number
  readonly default_column_width?: number
  readonly default_row_height_points: number
  readonly custom_height: boolean
  readonly zero_height: boolean
}

export interface NativeWorkbookNormalStyleV2 {
  readonly style_xf_id: number
  readonly font_id: number
  readonly font_name: string
  readonly font_size_points: number
  readonly font_bold: boolean
  readonly font_italic: boolean
  readonly font_record_sha256: string
}

export interface NativeWorkbookRowDimensionV2 {
  readonly row: number
  readonly height_points?: number
  readonly hidden: boolean
  readonly custom_height: boolean
  readonly style_id?: number
}

export interface NativeWorkbookColumnDimensionV2 {
  readonly column: number
  readonly end_column: number
  readonly width?: number
  readonly hidden: boolean
  readonly custom_width: boolean
  readonly best_fit: boolean
  readonly style_id?: number
}

export interface NativeWorkbookBorderSideV2 {
  readonly style: NativeBorderStyle
  readonly color: string
}

export interface NativeWorkbookBorderV2 {
  readonly origin: NativeBorderOrigin
  readonly border_id?: number
  readonly record_sha256?: string
  readonly left?: NativeWorkbookBorderSideV2
  readonly right?: NativeWorkbookBorderSideV2
  readonly top?: NativeWorkbookBorderSideV2
  readonly bottom?: NativeWorkbookBorderSideV2
}

export interface NativeWorkbookFillV2 {
  readonly origin: NativeBorderOrigin
  readonly fill_id?: number
  readonly record_sha256?: string
  readonly color?: string
}

export interface NativeWorkbookEffectiveStyleV2 {
  readonly number_format?: string
  readonly font_name?: string
  readonly font_size_points?: number
  readonly bold?: boolean
  readonly italic?: boolean
  readonly font_color?: string
  readonly fill_color?: string
  readonly fill?: NativeWorkbookFillV2
  readonly border?: NativeWorkbookBorderV2
  readonly horizontal_alignment?: NativeHorizontalAlignment
  readonly vertical_alignment?: NativeVerticalAlignment
  readonly wrap_text?: boolean
  readonly shrink_to_fit?: boolean
  readonly text_rotation?: 0 | 90 | 180 | 270
  readonly projection: NativeStyleProjection
  readonly unsupported: ReadonlyArray<NativeStyleUnsupportedCode>
}

export interface NativeWorkbookStyleV2 {
  readonly id: number
  readonly effective: NativeWorkbookEffectiveStyleV2
  readonly raw_projection_sha256: string
}

export interface NativeWorkbookSheetV2 {
  readonly id: string
  readonly name: string
  readonly order: number
  readonly state: NativeSheetState
  readonly part_name: string
  readonly sheet_format?: NativeWorkbookSheetFormatV2
  readonly rows: ReadonlyArray<NativeWorkbookRowDimensionV2>
  readonly columns: ReadonlyArray<NativeWorkbookColumnDimensionV2>
  readonly cells: ReadonlyArray<NativeWorkbookCellV2>
  readonly merged_ranges: ReadonlyArray<NativeWorkbookMergedRangeV2>
  readonly editable: boolean
  readonly refusal_code?: string
}
