// Code generated by scripts/generate-xlsx-native-contract.mjs; DO NOT EDIT.
// Source: ../../schemas/xlsx-native-v2.schema.json

package xlsxpatch

const NativeXLSXV2SchemaID = "https://schemas.injoffice.dev/xlsx/native-v2.schema.json"
const NativeXLSXV2SchemaSHA256 = "sha256:35297ab41a07d92fc705770dfdf10c717cde3400dde24e78955e0ce1bf4b017c"
const nativeXLSXV2SchemaProtocol = "injoffice.xlsx.native"
const nativeXLSXV2SchemaVersion = 2
const NativeXLSXV2MediaType = "application/vnd.injoffice.xlsx-native.v2+json"
const nativeXLSXV2SchemaMaxJsonBytes = 134217728
const nativeXLSXV2SchemaMaxJsonDepth = 256
const nativeXLSXV2SchemaMaxJsonTokens = 4000000
const nativeXLSXV2SchemaMaxSheets = 1024
const nativeXLSXV2SchemaMaxRows = 1048576
const nativeXLSXV2SchemaMaxColumns = 16384
const nativeXLSXV2SchemaMaxCells = 1000000
const nativeXLSXV2SchemaMaxMergedRanges = 100000
const nativeXLSXV2SchemaMaxStyles = 100000
const nativeXLSXV2SchemaMaxInventory = 10000
const nativeXLSXV2SchemaMaxTextBytes = 33554432
const nativeXLSXV2SchemaMaxPartBytes = 67108864
const nativeXLSXV2SchemaMaxIssues = 100

type nativeXLSXV2BindingShape struct {
	Properties []string
	Required   []string
	Types      map[string]string
}

var nativeXLSXV2BindingShapes = map[string]nativeXLSXV2BindingShape{
	"NativeWorkbookBorderSideV2":      {Properties: []string{"color", "style"}, Required: []string{"color", "style"}, Types: map[string]string{"color": "string", "style": "string"}},
	"NativeWorkbookBorderV2":          {Properties: []string{"border_id", "bottom", "left", "origin", "record_sha256", "right", "top"}, Required: []string{"origin"}, Types: map[string]string{"border_id": "integer", "bottom": "NativeWorkbookBorderSideV2", "left": "NativeWorkbookBorderSideV2", "origin": "string", "record_sha256": "string", "right": "NativeWorkbookBorderSideV2", "top": "NativeWorkbookBorderSideV2"}},
	"NativeWorkbookCapabilityV2":      {Properties: []string{"detail", "level", "name"}, Required: []string{"level", "name"}, Types: map[string]string{"detail": "string", "level": "string", "name": "string"}},
	"NativeWorkbookCellV2":            {Properties: []string{"column", "editable", "formula", "ooxml_type", "ref", "row", "style_id", "value"}, Required: []string{"column", "editable", "ref", "row", "style_id"}, Types: map[string]string{"column": "integer", "editable": "boolean", "formula": "NativeWorkbookFormulaV2", "ooxml_type": "string", "ref": "string", "row": "integer", "style_id": "integer", "value": "NativeWorkbookValueV2"}},
	"NativeWorkbookColumnDimensionV2": {Properties: []string{"best_fit", "column", "custom_width", "end_column", "hidden", "style_id", "width"}, Required: []string{"best_fit", "column", "custom_width", "end_column", "hidden"}, Types: map[string]string{"best_fit": "boolean", "column": "integer", "custom_width": "boolean", "end_column": "integer", "hidden": "boolean", "style_id": "integer", "width": "number"}},
	"NativeWorkbookEffectiveStyleV2":  {Properties: []string{"bold", "border", "fill", "fill_color", "font_color", "font_name", "font_size_points", "horizontal_alignment", "italic", "number_format", "projection", "shrink_to_fit", "text_rotation", "unsupported", "vertical_alignment", "wrap_text"}, Required: []string{"projection", "unsupported"}, Types: map[string]string{"bold": "boolean", "border": "NativeWorkbookBorderV2", "fill": "NativeWorkbookFillV2", "fill_color": "string", "font_color": "string", "font_name": "string", "font_size_points": "number", "horizontal_alignment": "string", "italic": "boolean", "number_format": "string", "projection": "string", "shrink_to_fit": "boolean", "text_rotation": "integer", "unsupported": "[]string", "vertical_alignment": "string", "wrap_text": "boolean"}},
	"NativeWorkbookFillV2":            {Properties: []string{"color", "fill_id", "origin", "record_sha256"}, Required: []string{"origin"}, Types: map[string]string{"color": "string", "fill_id": "integer", "origin": "string", "record_sha256": "string"}},
	"NativeWorkbookFormulaV2":         {Properties: []string{"cached", "ref", "shared_index", "text", "type"}, Required: []string{"text", "type"}, Types: map[string]string{"cached": "NativeWorkbookValueV2", "ref": "string", "shared_index": "integer", "text": "string", "type": "string"}},
	"NativeWorkbookMergedRangeV2":     {Properties: []string{"column", "editable", "end_column", "end_row", "ref", "row"}, Required: []string{"column", "editable", "end_column", "end_row", "ref", "row"}, Types: map[string]string{"column": "integer", "editable": "boolean", "end_column": "integer", "end_row": "integer", "ref": "string", "row": "integer"}},
	"NativeWorkbookNormalStyleV2":     {Properties: []string{"font_bold", "font_id", "font_italic", "font_name", "font_record_sha256", "font_size_points", "style_xf_id"}, Required: []string{"font_bold", "font_id", "font_italic", "font_name", "font_record_sha256", "font_size_points", "style_xf_id"}, Types: map[string]string{"font_bold": "boolean", "font_id": "integer", "font_italic": "boolean", "font_name": "string", "font_record_sha256": "string", "font_size_points": "number", "style_xf_id": "integer"}},
	"NativeWorkbookPassthroughPartV2": {Properties: []string{"byte_length", "content_type", "part_name", "policy", "sha256"}, Required: []string{"byte_length", "content_type", "part_name", "policy", "sha256"}, Types: map[string]string{"byte_length": "integer", "content_type": "string", "part_name": "string", "policy": "string", "sha256": "string"}},
	"NativeWorkbookRichRunV2":         {Properties: []string{"bold", "font_color", "font_name", "font_size_points", "italic", "text"}, Required: []string{"text"}, Types: map[string]string{"bold": "boolean", "font_color": "string", "font_name": "string", "font_size_points": "number", "italic": "boolean", "text": "string"}},
	"NativeWorkbookRowDimensionV2":    {Properties: []string{"custom_height", "height_points", "hidden", "row", "style_id"}, Required: []string{"custom_height", "hidden", "row"}, Types: map[string]string{"custom_height": "boolean", "height_points": "number", "hidden": "boolean", "row": "integer", "style_id": "integer"}},
	"NativeWorkbookSheetFormatV2":     {Properties: []string{"base_column_width", "custom_height", "default_column_width", "default_row_height_points", "zero_height"}, Required: []string{"custom_height", "default_row_height_points", "zero_height"}, Types: map[string]string{"base_column_width": "integer", "custom_height": "boolean", "default_column_width": "number", "default_row_height_points": "number", "zero_height": "boolean"}},
	"NativeWorkbookSheetV2":           {Properties: []string{"cells", "columns", "editable", "id", "merged_ranges", "name", "order", "part_name", "refusal_code", "rows", "sheet_format", "state"}, Required: []string{"cells", "columns", "editable", "id", "merged_ranges", "name", "order", "part_name", "rows", "state"}, Types: map[string]string{"cells": "[]NativeWorkbookCellV2", "columns": "[]NativeWorkbookColumnDimensionV2", "editable": "boolean", "id": "string", "merged_ranges": "[]NativeWorkbookMergedRangeV2", "name": "string", "order": "integer", "part_name": "string", "refusal_code": "string", "rows": "[]NativeWorkbookRowDimensionV2", "sheet_format": "NativeWorkbookSheetFormatV2", "state": "string"}},
	"NativeWorkbookSourceV2":          {Properties: []string{"authority", "dialect", "package_sha256", "workbook_part"}, Required: []string{"authority", "dialect", "package_sha256", "workbook_part"}, Types: map[string]string{"authority": "string", "dialect": "string", "package_sha256": "string", "workbook_part": "string"}},
	"NativeWorkbookStyleV2":           {Properties: []string{"effective", "id", "raw_projection_sha256"}, Required: []string{"effective", "id", "raw_projection_sha256"}, Types: map[string]string{"effective": "NativeWorkbookEffectiveStyleV2", "id": "integer", "raw_projection_sha256": "string"}},
	"NativeWorkbookUnsupportedV2":     {Properties: []string{"capability", "cell_ref", "code", "id", "message", "part_name", "preservation", "range_ref", "scope_id"}, Required: []string{"capability", "code", "id", "message", "preservation", "scope_id"}, Types: map[string]string{"capability": "string", "cell_ref": "string", "code": "string", "id": "string", "message": "string", "part_name": "string", "preservation": "string", "range_ref": "string", "scope_id": "string"}},
	"NativeWorkbookV2":                {Properties: []string{"capabilities", "date1904", "document_id", "normal_style", "passthrough_parts", "protocol", "revision", "schema_sha256", "sheets", "source", "styles", "unsupported", "version"}, Required: []string{"capabilities", "document_id", "passthrough_parts", "protocol", "revision", "schema_sha256", "sheets", "source", "styles", "unsupported", "version"}, Types: map[string]string{"capabilities": "[]NativeWorkbookCapabilityV2", "date1904": "boolean", "document_id": "string", "normal_style": "NativeWorkbookNormalStyleV2", "passthrough_parts": "[]NativeWorkbookPassthroughPartV2", "protocol": "string", "revision": "string", "schema_sha256": "string", "sheets": "[]NativeWorkbookSheetV2", "source": "NativeWorkbookSourceV2", "styles": "[]NativeWorkbookStyleV2", "unsupported": "[]NativeWorkbookUnsupportedV2", "version": "integer"}},
	"NativeWorkbookValueV2":           {Properties: []string{"kind", "lexical", "rich", "runs", "storage", "text"}, Required: []string{"kind", "rich", "storage"}, Types: map[string]string{"kind": "string", "lexical": "string", "rich": "boolean", "runs": "[]NativeWorkbookRichRunV2", "storage": "string", "text": "string"}},
}

var nativeXLSXV2SchemaUnsupportedClassifications = map[string]nativeUnsupportedClassification{
	"CELL_ATTRIBUTES":                    {capability: "cell-markup", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"CELL_EXTENSIONS":                    {capability: "extensions", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"CELL_METADATA":                      {capability: "cell-metadata", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"OPAQUE_CELL_MARKUP":                 {capability: "cell-markup", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"RICH_CELL_STRING":                   {capability: "rich-text", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"FORMULA_ATTRIBUTES":                 {capability: "formula-groups", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"FORMULA_SHARED":                     {capability: "formula-groups", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"FORMULA_ARRAY":                      {capability: "formula-groups", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"FORMULA_DATATABLE":                  {capability: "formula-groups", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"FORMULA_GROUP_RANGE":                {capability: "formula-groups", scope: "sheet", impact: nativeUnsupportedRangeImpact},
	"SHEET_PROTECTION":                   {capability: "protection", scope: "sheet", impact: nativeUnsupportedSheetImpact, refusalCode: "SHEET_PROTECTION"},
	"WORKSHEET_ATTRIBUTES":               {capability: "worksheet-features", scope: "sheet", impact: nativeUnsupportedSheetImpact, refusalCode: "UNSAFE_WORKSHEET_ATTRIBUTES"},
	"SHEET_DATA_ATTRIBUTES":              {capability: "worksheet-features", scope: "sheet", impact: nativeUnsupportedSheetImpact, refusalCode: "SHEET_DATA_ATTRIBUTES"},
	"SHEET_DECLARATION_ATTRIBUTES":       {capability: "workbook-features", scope: "sheet", impact: nativeUnsupportedSheetImpact, refusalCode: "SHEET_DECLARATION_ATTRIBUTES"},
	"COLS_ATTRIBUTES":                    {capability: "dimensions", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"SHEET_FORMAT_EXTRAS":                {capability: "dimensions", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"SHEET_VIEW_GEOMETRY":                {capability: "dimensions", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"COLUMN_DIMENSION_EXTRAS":            {capability: "dimensions", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"ROW_DIMENSION_EXTRAS":               {capability: "dimensions", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"ROW_EXTENSIONS":                     {capability: "extensions", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"INLINE_STRING_ATTRIBUTES":           {capability: "rich-text", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"MERGED_CELLS":                       {capability: "merges", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"CONDITIONAL_FORMATTING":             {capability: "conditional-formatting", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"DATA_VALIDATION":                    {capability: "data-validation", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"HYPERLINKS":                         {capability: "hyperlinks", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"DRAWING_REFERENCE":                  {capability: "drawings", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"TABLE_REFERENCE":                    {capability: "tables", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"WORKSHEET_EXTENSIONS":               {capability: "extensions", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"FOREIGN_WORKSHEET_MARKUP":           {capability: "extensions", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"UNMODELED_WORKSHEET_FEATURE":        {capability: "worksheet-features", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"RICH_SHARED_STRING":                 {capability: "rich-text", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"SHARED_STRING_TABLE_ATTRIBUTES":     {capability: "rich-text", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"SHARED_STRING_ITEM_ATTRIBUTES":      {capability: "rich-text", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"SHARED_STRING_TABLE_OPAQUE_CONTENT": {capability: "rich-text", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"WORKBOOK_ATTRIBUTES":                {capability: "workbook-features", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"SHEETS_ATTRIBUTES":                  {capability: "workbook-features", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"UNMODELED_WORKBOOK_FEATURE":         {capability: "workbook-features", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"EXTERNAL_RELATIONSHIP":              {capability: "external-links", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"STYLE_SHEET_ATTRIBUTES":             {capability: "styles", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"STYLE_TABLE_ATTRIBUTES":             {capability: "styles", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"STYLE_TABLE_OPAQUE_CONTENT":         {capability: "styles", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"STYLE_RECORD_ATTRIBUTES":            {capability: "styles", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"STYLE_FONT_OPAQUE_CONTENT":          {capability: "styles", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"STYLE_XF_OPAQUE_CONTENT":            {capability: "styles", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"STYLE_NUMBER_FORMAT":                {capability: "styles", scope: "style", impact: nativeUnsupportedNoImpact},
	"STYLE_FONT_COLOR":                   {capability: "styles", scope: "style", impact: nativeUnsupportedNoImpact},
	"STYLE_FILL":                         {capability: "styles", scope: "style", impact: nativeUnsupportedNoImpact},
	"STYLE_BORDER":                       {capability: "styles", scope: "style", impact: nativeUnsupportedNoImpact},
	"STYLE_HORIZONTAL_ALIGNMENT":         {capability: "styles", scope: "style", impact: nativeUnsupportedNoImpact},
	"STYLE_VERTICAL_ALIGNMENT":           {capability: "styles", scope: "style", impact: nativeUnsupportedNoImpact},
	"STYLE_ALIGNMENT_EXTENDED":           {capability: "styles", scope: "style", impact: nativeUnsupportedNoImpact},
	"CHART_CONTENT":                      {capability: "charts", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"PIVOT_OR_SLICER_CONTENT":            {capability: "pivots", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"DRAWING_OR_MEDIA_CONTENT":           {capability: "drawings", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"TABLE_CONTENT":                      {capability: "tables", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"COMMENT_CONTENT":                    {capability: "comments", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"EXTERNAL_LINK_CONTENT":              {capability: "external-links", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"MACRO_CONTENT":                      {capability: "macros", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"OPAQUE_PACKAGE_PART":                {capability: "opaque-parts", scope: "workbook", impact: nativeUnsupportedNoImpact},
}
