// Code generated by scripts/generate-xlsx-native-contract.mjs; DO NOT EDIT.
// Source: ../../schemas/xlsx-native-v1.schema.json

package xlsxpatch

const NativeXLSXSchemaID = "https://schemas.injoffice.dev/xlsx/native-v1.schema.json"
const NativeXLSXSchemaSHA256 = "8017eca7536f5d3d1e943fc04387ebad042c522b825f3b208ad6a5b0b05174ea"
const nativeXLSXSchemaProtocol = "injoffice.xlsx.native"
const nativeXLSXSchemaVersion = 1
const nativeXLSXSchemaMaxJsonBytes = 134217728
const nativeXLSXSchemaMaxJsonDepth = 256
const nativeXLSXSchemaMaxJsonTokens = 4000000
const nativeXLSXSchemaMaxSheets = 1024
const nativeXLSXSchemaMaxRows = 1048576
const nativeXLSXSchemaMaxColumns = 16384
const nativeXLSXSchemaMaxCells = 1000000
const nativeXLSXSchemaMaxMergedRanges = 100000
const nativeXLSXSchemaMaxStyles = 100000
const nativeXLSXSchemaMaxInventory = 10000
const nativeXLSXSchemaMaxTextBytes = 33554432
const nativeXLSXSchemaMaxPartBytes = 67108864
const nativeXLSXSchemaMaxIssues = 100

type nativeXLSXBindingShape struct {
	Properties []string
	Required   []string
	Types      map[string]string
}

var nativeXLSXBindingShapes = map[string]nativeXLSXBindingShape{
	"NativeWorkbookBorderSideV1":      {Properties: []string{"color", "style"}, Required: []string{"color", "style"}, Types: map[string]string{"color": "string", "style": "string"}},
	"NativeWorkbookBorderV1":          {Properties: []string{"border_id", "bottom", "left", "origin", "record_sha256", "right", "top"}, Required: []string{"origin"}, Types: map[string]string{"border_id": "integer", "bottom": "NativeWorkbookBorderSideV1", "left": "NativeWorkbookBorderSideV1", "origin": "string", "record_sha256": "string", "right": "NativeWorkbookBorderSideV1", "top": "NativeWorkbookBorderSideV1"}},
	"NativeWorkbookCapabilityV1":      {Properties: []string{"detail", "level", "name"}, Required: []string{"level", "name"}, Types: map[string]string{"detail": "string", "level": "string", "name": "string"}},
	"NativeWorkbookCellV1":            {Properties: []string{"column", "editable", "formula", "ooxml_type", "ref", "row", "style_id", "value"}, Required: []string{"column", "editable", "ref", "row", "style_id"}, Types: map[string]string{"column": "integer", "editable": "boolean", "formula": "NativeWorkbookFormulaV1", "ooxml_type": "string", "ref": "string", "row": "integer", "style_id": "integer", "value": "NativeWorkbookValueV1"}},
	"NativeWorkbookColumnDimensionV1": {Properties: []string{"best_fit", "column", "custom_width", "end_column", "hidden", "style_id", "width"}, Required: []string{"best_fit", "column", "custom_width", "end_column", "hidden"}, Types: map[string]string{"best_fit": "boolean", "column": "integer", "custom_width": "boolean", "end_column": "integer", "hidden": "boolean", "style_id": "integer", "width": "number"}},
	"NativeWorkbookEffectiveStyleV1":  {Properties: []string{"bold", "border", "fill", "fill_color", "font_color", "font_name", "font_size_points", "horizontal_alignment", "italic", "number_format", "projection", "unsupported", "vertical_alignment", "wrap_text"}, Required: []string{"projection", "unsupported"}, Types: map[string]string{"bold": "boolean", "border": "NativeWorkbookBorderV1", "fill": "NativeWorkbookFillV1", "fill_color": "string", "font_color": "string", "font_name": "string", "font_size_points": "number", "horizontal_alignment": "string", "italic": "boolean", "number_format": "string", "projection": "string", "unsupported": "[]string", "vertical_alignment": "string", "wrap_text": "boolean"}},
	"NativeWorkbookFillV1":            {Properties: []string{"color", "fill_id", "origin", "record_sha256"}, Required: []string{"origin"}, Types: map[string]string{"color": "string", "fill_id": "integer", "origin": "string", "record_sha256": "string"}},
	"NativeWorkbookFormulaV1":         {Properties: []string{"cached", "ref", "shared_index", "text", "type"}, Required: []string{"text", "type"}, Types: map[string]string{"cached": "NativeWorkbookValueV1", "ref": "string", "shared_index": "integer", "text": "string", "type": "string"}},
	"NativeWorkbookMergedRangeV1":     {Properties: []string{"column", "editable", "end_column", "end_row", "ref", "row"}, Required: []string{"column", "editable", "end_column", "end_row", "ref", "row"}, Types: map[string]string{"column": "integer", "editable": "boolean", "end_column": "integer", "end_row": "integer", "ref": "string", "row": "integer"}},
	"NativeWorkbookNormalStyleV1":     {Properties: []string{"font_bold", "font_id", "font_italic", "font_name", "font_record_sha256", "font_size_points", "style_xf_id"}, Required: []string{"font_bold", "font_id", "font_italic", "font_name", "font_record_sha256", "font_size_points", "style_xf_id"}, Types: map[string]string{"font_bold": "boolean", "font_id": "integer", "font_italic": "boolean", "font_name": "string", "font_record_sha256": "string", "font_size_points": "number", "style_xf_id": "integer"}},
	"NativeWorkbookPassthroughPartV1": {Properties: []string{"byte_length", "content_type", "part_name", "policy", "sha256"}, Required: []string{"byte_length", "content_type", "part_name", "policy", "sha256"}, Types: map[string]string{"byte_length": "integer", "content_type": "string", "part_name": "string", "policy": "string", "sha256": "string"}},
	"NativeWorkbookRowDimensionV1":    {Properties: []string{"custom_height", "height_points", "hidden", "row", "style_id"}, Required: []string{"custom_height", "hidden", "row"}, Types: map[string]string{"custom_height": "boolean", "height_points": "number", "hidden": "boolean", "row": "integer", "style_id": "integer"}},
	"NativeWorkbookSheetFormatV1":     {Properties: []string{"base_column_width", "custom_height", "default_column_width", "default_row_height_points", "zero_height"}, Required: []string{"custom_height", "default_row_height_points", "zero_height"}, Types: map[string]string{"base_column_width": "integer", "custom_height": "boolean", "default_column_width": "number", "default_row_height_points": "number", "zero_height": "boolean"}},
	"NativeWorkbookSheetV1":           {Properties: []string{"cells", "columns", "editable", "id", "merged_ranges", "name", "order", "part_name", "refusal_code", "rows", "sheet_format", "state"}, Required: []string{"cells", "columns", "editable", "id", "merged_ranges", "name", "order", "part_name", "rows", "state"}, Types: map[string]string{"cells": "[]NativeWorkbookCellV1", "columns": "[]NativeWorkbookColumnDimensionV1", "editable": "boolean", "id": "string", "merged_ranges": "[]NativeWorkbookMergedRangeV1", "name": "string", "order": "integer", "part_name": "string", "refusal_code": "string", "rows": "[]NativeWorkbookRowDimensionV1", "sheet_format": "NativeWorkbookSheetFormatV1", "state": "string"}},
	"NativeWorkbookSourceV1":          {Properties: []string{"authority", "dialect", "package_sha256", "workbook_part"}, Required: []string{"authority", "dialect", "package_sha256", "workbook_part"}, Types: map[string]string{"authority": "string", "dialect": "string", "package_sha256": "string", "workbook_part": "string"}},
	"NativeWorkbookStyleV1":           {Properties: []string{"effective", "id", "raw_projection_sha256"}, Required: []string{"effective", "id", "raw_projection_sha256"}, Types: map[string]string{"effective": "NativeWorkbookEffectiveStyleV1", "id": "integer", "raw_projection_sha256": "string"}},
	"NativeWorkbookUnsupportedV1":     {Properties: []string{"capability", "cell_ref", "code", "id", "message", "part_name", "preservation", "range_ref", "scope_id"}, Required: []string{"capability", "code", "id", "message", "preservation", "scope_id"}, Types: map[string]string{"capability": "string", "cell_ref": "string", "code": "string", "id": "string", "message": "string", "part_name": "string", "preservation": "string", "range_ref": "string", "scope_id": "string"}},
	"NativeWorkbookV1":                {Properties: []string{"capabilities", "document_id", "normal_style", "passthrough_parts", "protocol", "revision", "sheets", "source", "styles", "unsupported", "version"}, Required: []string{"capabilities", "document_id", "passthrough_parts", "protocol", "revision", "sheets", "source", "styles", "unsupported", "version"}, Types: map[string]string{"capabilities": "[]NativeWorkbookCapabilityV1", "document_id": "string", "normal_style": "NativeWorkbookNormalStyleV1", "passthrough_parts": "[]NativeWorkbookPassthroughPartV1", "protocol": "string", "revision": "string", "sheets": "[]NativeWorkbookSheetV1", "source": "NativeWorkbookSourceV1", "styles": "[]NativeWorkbookStyleV1", "unsupported": "[]NativeWorkbookUnsupportedV1", "version": "integer"}},
	"NativeWorkbookValueV1":           {Properties: []string{"kind", "lexical", "rich", "storage", "text"}, Required: []string{"kind", "rich", "storage"}, Types: map[string]string{"kind": "string", "lexical": "string", "rich": "boolean", "storage": "string", "text": "string"}},
}

var nativeXLSXSchemaUnsupportedClassifications = map[string]nativeUnsupportedClassification{
	"CELL_ATTRIBUTES":                    {capability: "cell-markup", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"CELL_EXTENSIONS":                    {capability: "extensions", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"CELL_METADATA":                      {capability: "cell-metadata", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"OPAQUE_CELL_MARKUP":                 {capability: "cell-markup", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"RICH_CELL_STRING":                   {capability: "rich-text", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"FORMULA_ATTRIBUTES":                 {capability: "formula-groups", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"FORMULA_SHARED":                     {capability: "formula-groups", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"FORMULA_ARRAY":                      {capability: "formula-groups", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"FORMULA_DATATABLE":                  {capability: "formula-groups", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"FORMULA_GROUP_RANGE":                {capability: "formula-groups", scope: "sheet", impact: nativeUnsupportedRangeImpact},
	"SHEET_PROTECTION":                   {capability: "protection", scope: "sheet", impact: nativeUnsupportedSheetImpact, refusalCode: "SHEET_PROTECTION"},
	"WORKSHEET_ATTRIBUTES":               {capability: "worksheet-features", scope: "sheet", impact: nativeUnsupportedSheetImpact, refusalCode: "UNSAFE_WORKSHEET_ATTRIBUTES"},
	"SHEET_DATA_ATTRIBUTES":              {capability: "worksheet-features", scope: "sheet", impact: nativeUnsupportedSheetImpact, refusalCode: "SHEET_DATA_ATTRIBUTES"},
	"SHEET_DECLARATION_ATTRIBUTES":       {capability: "workbook-features", scope: "sheet", impact: nativeUnsupportedSheetImpact, refusalCode: "SHEET_DECLARATION_ATTRIBUTES"},
	"COLS_ATTRIBUTES":                    {capability: "dimensions", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"SHEET_FORMAT_EXTRAS":                {capability: "dimensions", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"SHEET_VIEW_GEOMETRY":                {capability: "dimensions", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"COLUMN_DIMENSION_EXTRAS":            {capability: "dimensions", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"ROW_DIMENSION_EXTRAS":               {capability: "dimensions", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"ROW_EXTENSIONS":                     {capability: "extensions", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"INLINE_STRING_ATTRIBUTES":           {capability: "rich-text", scope: "sheet", impact: nativeUnsupportedCellImpact},
	"MERGED_CELLS":                       {capability: "merges", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"CONDITIONAL_FORMATTING":             {capability: "conditional-formatting", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"DATA_VALIDATION":                    {capability: "data-validation", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"HYPERLINKS":                         {capability: "hyperlinks", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"DRAWING_REFERENCE":                  {capability: "drawings", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"TABLE_REFERENCE":                    {capability: "tables", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"WORKSHEET_EXTENSIONS":               {capability: "extensions", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"FOREIGN_WORKSHEET_MARKUP":           {capability: "extensions", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"UNMODELED_WORKSHEET_FEATURE":        {capability: "worksheet-features", scope: "sheet", impact: nativeUnsupportedNoImpact},
	"RICH_SHARED_STRING":                 {capability: "rich-text", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"SHARED_STRING_TABLE_ATTRIBUTES":     {capability: "rich-text", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"SHARED_STRING_ITEM_ATTRIBUTES":      {capability: "rich-text", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"SHARED_STRING_TABLE_OPAQUE_CONTENT": {capability: "rich-text", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"WORKBOOK_ATTRIBUTES":                {capability: "workbook-features", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"SHEETS_ATTRIBUTES":                  {capability: "workbook-features", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"UNMODELED_WORKBOOK_FEATURE":         {capability: "workbook-features", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"EXTERNAL_RELATIONSHIP":              {capability: "external-links", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"STYLE_SHEET_ATTRIBUTES":             {capability: "styles", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"STYLE_TABLE_ATTRIBUTES":             {capability: "styles", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"STYLE_TABLE_OPAQUE_CONTENT":         {capability: "styles", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"STYLE_RECORD_ATTRIBUTES":            {capability: "styles", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"STYLE_FONT_OPAQUE_CONTENT":          {capability: "styles", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"STYLE_XF_OPAQUE_CONTENT":            {capability: "styles", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"STYLE_NUMBER_FORMAT":                {capability: "styles", scope: "style", impact: nativeUnsupportedNoImpact},
	"STYLE_FONT_COLOR":                   {capability: "styles", scope: "style", impact: nativeUnsupportedNoImpact},
	"STYLE_FILL":                         {capability: "styles", scope: "style", impact: nativeUnsupportedNoImpact},
	"STYLE_BORDER":                       {capability: "styles", scope: "style", impact: nativeUnsupportedNoImpact},
	"STYLE_HORIZONTAL_ALIGNMENT":         {capability: "styles", scope: "style", impact: nativeUnsupportedNoImpact},
	"STYLE_VERTICAL_ALIGNMENT":           {capability: "styles", scope: "style", impact: nativeUnsupportedNoImpact},
	"STYLE_ALIGNMENT_EXTENDED":           {capability: "styles", scope: "style", impact: nativeUnsupportedNoImpact},
	"CHART_CONTENT":                      {capability: "charts", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"PIVOT_OR_SLICER_CONTENT":            {capability: "pivots", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"DRAWING_OR_MEDIA_CONTENT":           {capability: "drawings", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"TABLE_CONTENT":                      {capability: "tables", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"COMMENT_CONTENT":                    {capability: "comments", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"EXTERNAL_LINK_CONTENT":              {capability: "external-links", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"MACRO_CONTENT":                      {capability: "macros", scope: "workbook", impact: nativeUnsupportedNoImpact},
	"OPAQUE_PACKAGE_PART":                {capability: "opaque-parts", scope: "workbook", impact: nativeUnsupportedNoImpact},
}
