import type {NativeDocxSectionV1} from '../../../packages/docs/src/nativeContract'
export type PagePatch={width_twips:number;height_twips:number;orientation:'portrait'|'landscape';margin_top_twips:number;margin_right_twips:number;margin_bottom_twips:number;margin_left_twips:number}
const sizes=[{name:'Letter',width:12240,height:15840},{name:'A4',width:11906,height:16838},{name:'Legal',width:12240,height:20160},{name:'A5',width:8391,height:11906}]
export function pagePatch(section:NativeDocxSectionV1):PagePatch{const page=section.page;return {width_twips:page.width_twips,height_twips:page.height_twips,orientation:page.orientation,margin_top_twips:page.margins.top_twips,margin_right_twips:page.margins.right_twips,margin_bottom_twips:page.margins.bottom_twips,margin_left_twips:page.margins.left_twips}}
export default function PageLayoutControl({section,disabled,onChange}:{section?:NativeDocxSectionV1;disabled:boolean;onChange(patch:PagePatch):void}){
 if(!section)return null
 if(!section.edit_policy?.allowed_operations.includes('section.page.patch'))return <p className="office-page-layout-note">Page settings are read only for this document’s section structure.</p>
 const value=pagePatch(section),landscape=value.orientation==='landscape',size=sizes.find(item=>value.width_twips===(landscape?item.height:item.width)&&value.height_twips===(landscape?item.width:item.height))
 return <div className="paragraph-toolbar office-page-layout" aria-label="Page settings">
  <label>Paper size<select aria-label="Document paper size" value={size?.name??''} disabled={disabled} onChange={event=>{const next=sizes.find(item=>item.name===event.target.value);if(next)onChange({...value,width_twips:landscape?next.height:next.width,height_twips:landscape?next.width:next.height})}}>{!size&&<option value="">Custom · {(value.width_twips/1440).toFixed(2)} × {(value.height_twips/1440).toFixed(2)} in</option>}{sizes.map(item=><option key={item.name}>{item.name}</option>)}</select></label>
  <label>Orientation<select aria-label="Document page orientation" value={value.orientation} disabled={disabled} onChange={event=>onChange({...value,orientation:event.target.value as PagePatch['orientation'],width_twips:value.height_twips,height_twips:value.width_twips})}><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label>
  {(['top','right','bottom','left'] as const).map(edge=>{const key=`margin_${edge}_twips` as const,amount=value[key],options=[...new Set([amount,0,360,720,1080,1440,1800,2160,2520,2880,3600,4320])].sort((a,b)=>a-b);return <label key={edge}>{edge[0].toUpperCase()+edge.slice(1)} margin<select aria-label={`${edge} page margin`} value={amount} disabled={disabled} onChange={event=>onChange({...value,[key]:Number(event.target.value)})}>{options.map(option=><option key={option} value={option}>{Number((option/1440).toFixed(3))} in</option>)}</select></label>})}
  <span>Page margins in inches · header/footer distances preserved</span>
 </div>
}
