// The curated target set for the formula-coverage audit (Phase 7): the
// functions agents and business users actually reach for, each with a sample
// invocation that is VALID against the audit fixture (see audit.test.ts:
// A1:A5 = 1..4 with header, B = text, C = mixed, D = dates).
//
// This is the published-matrix source of truth: the audit evaluates every
// entry in the REAL engine and fails if coverage regresses. Univer OSS
// declares 535 functions — this list is the "do the ones that matter
// actually compute" proof on top.

export interface TargetFunction {
  name: string
  formula: string
}

export const TARGET_FUNCTIONS: TargetFunction[] = [
  // Math & aggregation
  { name: 'SUM', formula: '=SUM(A2:A5)' },
  { name: 'SUMIF', formula: '=SUMIF(A2:A5,">2")' },
  { name: 'SUMIFS', formula: '=SUMIFS(A2:A5,A2:A5,">1",A2:A5,"<4")' },
  { name: 'SUMPRODUCT', formula: '=SUMPRODUCT(A2:A5,A2:A5)' },
  { name: 'PRODUCT', formula: '=PRODUCT(A2:A3)' },
  { name: 'ABS', formula: '=ABS(-3)' },
  { name: 'ROUND', formula: '=ROUND(3.14159,2)' },
  { name: 'ROUNDUP', formula: '=ROUNDUP(3.14,1)' },
  { name: 'ROUNDDOWN', formula: '=ROUNDDOWN(3.19,1)' },
  { name: 'INT', formula: '=INT(3.7)' },
  { name: 'MOD', formula: '=MOD(10,3)' },
  { name: 'POWER', formula: '=POWER(2,8)' },
  { name: 'SQRT', formula: '=SQRT(16)' },
  { name: 'EXP', formula: '=EXP(1)' },
  { name: 'LN', formula: '=LN(10)' },
  { name: 'LOG', formula: '=LOG(100,10)' },
  { name: 'LOG10', formula: '=LOG10(100)' },
  { name: 'CEILING', formula: '=CEILING(2.1,1)' },
  { name: 'FLOOR', formula: '=FLOOR(2.9,1)' },
  { name: 'MROUND', formula: '=MROUND(7,3)' },
  { name: 'TRUNC', formula: '=TRUNC(8.97,1)' },
  { name: 'SIGN', formula: '=SIGN(-9)' },
  { name: 'RAND', formula: '=RAND()' },
  { name: 'RANDBETWEEN', formula: '=RANDBETWEEN(1,10)' },
  { name: 'PI', formula: '=PI()' },
  { name: 'SUBTOTAL', formula: '=SUBTOTAL(9,A2:A5)' },
  { name: 'AGGREGATE', formula: '=AGGREGATE(9,6,A2:A5)' },
  // Statistical
  { name: 'AVERAGE', formula: '=AVERAGE(A2:A5)' },
  { name: 'AVERAGEIF', formula: '=AVERAGEIF(A2:A5,">1")' },
  { name: 'AVERAGEIFS', formula: '=AVERAGEIFS(A2:A5,A2:A5,">1")' },
  { name: 'COUNT', formula: '=COUNT(A2:A5)' },
  { name: 'COUNTA', formula: '=COUNTA(B2:B5)' },
  { name: 'COUNTBLANK', formula: '=COUNTBLANK(A2:A6)' },
  { name: 'COUNTIF', formula: '=COUNTIF(A2:A5,">2")' },
  { name: 'COUNTIFS', formula: '=COUNTIFS(A2:A5,">1",A2:A5,"<4")' },
  { name: 'MAX', formula: '=MAX(A2:A5)' },
  { name: 'MIN', formula: '=MIN(A2:A5)' },
  { name: 'MEDIAN', formula: '=MEDIAN(A2:A5)' },
  { name: 'MODE.SNGL', formula: '=MODE.SNGL(F1:F3)' },
  { name: 'STDEV.P', formula: '=STDEV.P(A2:A5)' },
  { name: 'STDEV.S', formula: '=STDEV.S(A2:A5)' },
  { name: 'VAR.P', formula: '=VAR.P(A2:A5)' },
  { name: 'VAR.S', formula: '=VAR.S(A2:A5)' },
  { name: 'LARGE', formula: '=LARGE(A2:A5,2)' },
  { name: 'SMALL', formula: '=SMALL(A2:A5,2)' },
  { name: 'RANK', formula: '=RANK(A3,A2:A5)' },
  { name: 'PERCENTILE.INC', formula: '=PERCENTILE.INC(A2:A5,0.5)' },
  { name: 'QUARTILE.INC', formula: '=QUARTILE.INC(A2:A5,1)' },
  { name: 'CORREL', formula: '=CORREL(A2:A5,A2:A5)' },
  { name: 'FORECAST.LINEAR', formula: '=FORECAST.LINEAR(5,A2:A5,A2:A5)' },
  { name: 'SLOPE', formula: '=SLOPE(A2:A5,A2:A5)' },
  { name: 'INTERCEPT', formula: '=INTERCEPT(A2:A5,A2:A5)' },
  { name: 'TREND', formula: '=TREND(A2:A5)' },
  { name: 'GEOMEAN', formula: '=GEOMEAN(A2:A5)' },
  // Logical
  { name: 'IF', formula: '=IF(1>0,"yes","no")' },
  { name: 'IFS', formula: '=IFS(1>2,"a",1>0,"b")' },
  { name: 'IFERROR', formula: '=IFERROR(1/0,"safe")' },
  { name: 'IFNA', formula: '=IFNA(NA(),"safe")' },
  { name: 'AND', formula: '=AND(TRUE,1>0)' },
  { name: 'OR', formula: '=OR(FALSE,1>0)' },
  { name: 'NOT', formula: '=NOT(FALSE)' },
  { name: 'XOR', formula: '=XOR(TRUE,FALSE)' },
  { name: 'SWITCH', formula: '=SWITCH(2,1,"one",2,"two","other")' },
  { name: 'LET', formula: '=LET(x,2,x*3)' },
  { name: 'LAMBDA', formula: '=LAMBDA(x,x+1)(41)' },
  // Lookup & reference
  { name: 'VLOOKUP', formula: '=VLOOKUP(2,A2:B5,2,FALSE)' },
  { name: 'HLOOKUP', formula: '=HLOOKUP(1,A2:A5,1,TRUE)' },
  { name: 'XLOOKUP', formula: '=XLOOKUP(2,A2:A5,B2:B5)' },
  { name: 'LOOKUP', formula: '=LOOKUP(2,A2:A5,B2:B5)' },
  { name: 'INDEX', formula: '=INDEX(A2:B5,2,1)' },
  { name: 'MATCH', formula: '=MATCH(3,A2:A5,0)' },
  { name: 'XMATCH', formula: '=XMATCH(3,A2:A5)' },
  { name: 'OFFSET', formula: '=OFFSET(A2,1,0)' },
  { name: 'INDIRECT', formula: '=INDIRECT("A2")' },
  { name: 'CHOOSE', formula: '=CHOOSE(2,"a","b","c")' },
  { name: 'ROW', formula: '=ROW(A3)' },
  { name: 'COLUMN', formula: '=COLUMN(B1)' },
  { name: 'ROWS', formula: '=ROWS(A2:A5)' },
  { name: 'COLUMNS', formula: '=COLUMNS(A1:B1)' },
  { name: 'UNIQUE', formula: '=UNIQUE(A2:A5)' },
  { name: 'SORT', formula: '=SORT(A2:A5)' },
  { name: 'FILTER', formula: '=FILTER(A2:A5,A2:A5>1)' },
  { name: 'SEQUENCE', formula: '=SEQUENCE(3)' },
  { name: 'TRANSPOSE', formula: '=TRANSPOSE(A2:A3)' },
  // Text
  { name: 'CONCAT', formula: '=CONCAT("a","b")' },
  { name: 'CONCATENATE', formula: '=CONCATENATE("a","b")' },
  { name: 'TEXTJOIN', formula: '=TEXTJOIN(",",TRUE,"a","b")' },
  { name: 'LEFT', formula: '=LEFT("hello",2)' },
  { name: 'RIGHT', formula: '=RIGHT("hello",2)' },
  { name: 'MID', formula: '=MID("hello",2,3)' },
  { name: 'LEN', formula: '=LEN("hello")' },
  { name: 'LOWER', formula: '=LOWER("HELLO")' },
  { name: 'UPPER', formula: '=UPPER("hello")' },
  { name: 'PROPER', formula: '=PROPER("hello world")' },
  { name: 'TRIM', formula: '=TRIM("  x  ")' },
  { name: 'SUBSTITUTE', formula: '=SUBSTITUTE("aab","a","x")' },
  { name: 'REPLACE', formula: '=REPLACE("abcdef",2,3,"XY")' },
  { name: 'FIND', formula: '=FIND("l","hello")' },
  { name: 'SEARCH', formula: '=SEARCH("L","hello")' },
  { name: 'TEXT', formula: '=TEXT(0.285,"0.0%")' },
  { name: 'VALUE', formula: '=VALUE("42")' },
  { name: 'NUMBERVALUE', formula: '=NUMBERVALUE("1,250.5",".",",")' },
  { name: 'REPT', formula: '=REPT("ab",3)' },
  { name: 'CHAR', formula: '=CHAR(65)' },
  { name: 'CODE', formula: '=CODE("A")' },
  { name: 'EXACT', formula: '=EXACT("a","a")' },
  { name: 'TEXTSPLIT', formula: '=TEXTSPLIT("a,b",",")' },
  { name: 'TEXTBEFORE', formula: '=TEXTBEFORE("a-b","-")' },
  { name: 'TEXTAFTER', formula: '=TEXTAFTER("a-b","-")' },
  // Date & time
  { name: 'TODAY', formula: '=TODAY()' },
  { name: 'NOW', formula: '=NOW()' },
  { name: 'DATE', formula: '=DATE(2026,8,21)' },
  { name: 'YEAR', formula: '=YEAR(DATE(2026,8,21))' },
  { name: 'MONTH', formula: '=MONTH(DATE(2026,8,21))' },
  { name: 'DAY', formula: '=DAY(DATE(2026,8,21))' },
  { name: 'HOUR', formula: '=HOUR(0.75)' },
  { name: 'MINUTE', formula: '=MINUTE(0.51)' },
  { name: 'WEEKDAY', formula: '=WEEKDAY(DATE(2026,8,21))' },
  { name: 'WEEKNUM', formula: '=WEEKNUM(DATE(2026,8,21))' },
  { name: 'EOMONTH', formula: '=EOMONTH(DATE(2026,8,21),0)' },
  { name: 'EDATE', formula: '=EDATE(DATE(2026,8,21),1)' },
  { name: 'DATEDIF', formula: '=DATEDIF(DATE(2026,1,1),DATE(2026,8,21),"d")' },
  { name: 'NETWORKDAYS', formula: '=NETWORKDAYS(DATE(2026,8,1),DATE(2026,8,21))' },
  { name: 'WORKDAY', formula: '=WORKDAY(DATE(2026,8,21),5)' },
  { name: 'DAYS', formula: '=DAYS(DATE(2026,8,21),DATE(2026,8,1))' },
  { name: 'DATEVALUE', formula: '=DATEVALUE("2026-08-21")' },
  // Information
  { name: 'ISBLANK', formula: '=ISBLANK(A6)' },
  { name: 'ISNUMBER', formula: '=ISNUMBER(A2)' },
  { name: 'ISTEXT', formula: '=ISTEXT(B2)' },
  { name: 'ISERROR', formula: '=ISERROR(1/0)' },
  { name: 'ISNA', formula: '=ISNA(NA())' },
  { name: 'ISEVEN', formula: '=ISEVEN(4)' },
  { name: 'ISODD', formula: '=ISODD(3)' },
  { name: 'N', formula: '=N(TRUE)' },
  { name: 'NA', formula: '=NA()' },
  // Financial
  { name: 'PMT', formula: '=PMT(0.05/12,60,10000)' },
  { name: 'FV', formula: '=FV(0.05/12,60,-100)' },
  { name: 'PV', formula: '=PV(0.05/12,60,-100)' },
  { name: 'NPV', formula: '=NPV(0.1,100,200)' },
  { name: 'IRR', formula: '=IRR(E2:E4)' },
  { name: 'RATE', formula: '=RATE(60,-100,5000)' },
  { name: 'NPER', formula: '=NPER(0.05/12,-100,5000)' },
]
