import { afterEach, describe, expect, it, vi } from 'vitest'
import { createDemoRetention } from './demoRetention'

afterEach(() => vi.useRealTimers())
describe('demo retention', () => {
  it('releases an untouched offscreen demo after a grace period', () => {
    vi.useFakeTimers()
    const release = vi.fn()
    const retention = createDemoRetention(release)
    retention.setLoaded(true)
    retention.setVisible(false)
    vi.advanceTimersByTime(29_999)
    expect(release).not.toHaveBeenCalled()
    vi.advanceTimersByTime(1)
    expect(release).toHaveBeenCalledTimes(1)
  })
  it('never evicts interacted editors, even if interaction races the timer', () => {
    vi.useFakeTimers()
    const release = vi.fn()
    const retention = createDemoRetention(release)
    retention.setVisible(false)
    retention.setLoaded(true)
    vi.advanceTimersByTime(29_999)
    retention.touch()
    vi.advanceTimersByTime(120_000)
    expect(release).not.toHaveBeenCalled()
  })
  it('cancels release on return or unmount, and restarts the grace period', () => {
    vi.useFakeTimers()
    const release = vi.fn()
    const retention = createDemoRetention(release)
    retention.setLoaded(true)
    retention.setVisible(false)
    vi.advanceTimersByTime(20_000)
    retention.setVisible(true)
    vi.advanceTimersByTime(30_000)
    expect(release).not.toHaveBeenCalled()
    retention.setVisible(false)
    vi.advanceTimersByTime(20_000)
    retention.dispose()
    vi.advanceTimersByTime(30_000)
    expect(release).not.toHaveBeenCalled()
  })
})
